import type { SectorMatrix } from './types';

/** Matriz profunda agricultura — proposta v0 (co-construção). */
export const AGRICULTURE_MATRIX: SectorMatrix = {
  sectorId: 'agriculture',
  items: [
    {
      id: 'AGR-GOB-01',
      blockId: 'gob',
      blockLabel: { es: 'Gobernanza, tierra y decisión', pt: 'Governança, terra e decisão', en: 'Governance, land & decision' },
      areaName: { es: 'Titularidad y uso de la tierra', pt: 'Titularidade e uso da terra', en: 'Land tenure' },
      prompt: {
        es: '¿Cuál es la estructura jurídica y documental de la tierra cultivada (propiedad, arriendo, comodato, reforma, posesión)? ¿Existe inventario parcelario con área útil vs. total?',
        pt: 'Qual é a estrutura jurídica e documental da terra cultivada (propriedade, arrendamento, comodato, reforma, posse)? Existe inventário parcelar com área útil vs. total?',
        en: 'What is the legal/documentary structure of cultivated land, and is there a parcel inventory of usable vs total area?',
      },
      help: {
        es: 'Evidencia: escrituras, contratos, croquis/GPS, % área efectiva',
        pt: 'Evidência: escrituras, contratos, croqui/GPS, % área efetiva',
        en: 'Evidence: deeds, leases, GPS sketch, usable %',
      },
      level5: {
        es: 'Cadastro georreferenciado + contratos vigentes + área útil auditable',
        pt: 'Cadastro georreferenciado + contratos vigentes + área útil auditável',
        en: 'Georeferenced cadastre + active leases + auditable usable area',
      },
      pillarSlug: 'risk',
      weight: 1.2,
    },
    {
      id: 'AGR-GOB-02',
      blockId: 'gob',
      blockLabel: { es: 'Gobernanza, tierra y decisión', pt: 'Governança, terra e decisão', en: 'Governance, land & decision' },
      areaName: { es: 'Agua y derechos hídricos', pt: 'Água e direitos hídricos', en: 'Water rights' },
      prompt: {
        es: '¿Qué fuentes de agua usa y qué derechos/concesiones/límites de caudal existen? ¿Se mide el consumo por ciclo?',
        pt: 'Que fontes de água usa e que direitos/concessões/limites de vazão existem? Mede o consumo por ciclo?',
        en: 'What water sources and rights/limits exist, and is consumption measured per cycle?',
      },
      help: {
        es: 'Evidencia: concesiones, bombas, m³/ciclo, conflictos de uso',
        pt: 'Evidência: concessões, bombas, m³/ciclo, conflitos de uso',
        en: 'Evidence: permits, pumps, m³/cycle, conflicts',
      },
      level5: {
        es: 'Derecho formal + medición + plan de asignación por cultivo/ciclo',
        pt: 'Direito formal + medição + plano de alocação por cultura/ciclo',
        en: 'Formal right + metering + allocation plan by crop/cycle',
      },
      pillarSlug: 'operations',
      weight: 1.25,
    },
    {
      id: 'AGR-GOB-03',
      blockId: 'gob',
      blockLabel: { es: 'Gobernanza, tierra y decisión', pt: 'Governança, terra e decisão', en: 'Governance, land & decision' },
      areaName: { es: 'Plan 12–24 meses', pt: 'Plano 12–24 meses', en: '12–24 month plan' },
      prompt: {
        es: '¿Existe un plan de producción y financiero a 12–24 meses o las decisiones son ciclo a ciclo según liquidez y clima?',
        pt: 'Existe um plano de produção e financeiro a 12–24 meses ou as decisões são ciclo a ciclo conforme liquidez e clima?',
        en: 'Is there a 12–24 month production/finance plan, or only cycle-by-cycle decisions?',
      },
      help: {
        es: 'Evidencia: plan escrito, metas, revisión trimestral',
        pt: 'Evidência: plano escrito, metas, revisão trimestral',
        en: 'Evidence: written plan, goals, quarterly review',
      },
      level5: {
        es: 'Plan con KPIs, revisión trimestral y escenarios clima/precio',
        pt: 'Plano com KPIs, revisão trimestral e cenários clima/preço',
        en: 'KPI plan, quarterly review, climate/price scenarios',
      },
      pillarSlug: 'strategy',
      weight: 1.3,
    },
    {
      id: 'AGR-GOB-04',
      blockId: 'gob',
      blockLabel: { es: 'Gobernanza, tierra y decisión', pt: 'Governança, terra e decisão', en: 'Governance, land & decision' },
      areaName: { es: 'Delegación de decisiones', pt: 'Delegação de decisões', en: 'Decision delegation' },
      prompt: {
        es: '¿Qué decisiones están solo en el productor y dónde están los cuellos de botella en pico de cosecha?',
        pt: 'Que decisões estão só no produtor e onde estão os gargalos no pico de colheita?',
        en: 'Which decisions sit only with the producer, and where are peak-harvest bottlenecks?',
      },
      help: {
        es: 'Evidencia: mapa RACI informal, quién autoriza qué',
        pt: 'Evidência: mapa RACI informal, quem autoriza o quê',
        en: 'Evidence: informal RACI, who authorizes what',
      },
      level5: {
        es: 'Roles escritos + límites de autonomía + backup de decisión',
        pt: 'Papéis escritos + limites de autonomia + backup de decisão',
        en: 'Written roles + autonomy limits + decision backup',
      },
      pillarSlug: 'people',
      weight: 1.1,
    },
    {
      id: 'AGR-AGR-01',
      blockId: 'agr',
      blockLabel: { es: 'Agronomía y planificación', pt: 'Agronomia e planeamento', en: 'Agronomy & planning' },
      areaName: { es: 'Calendario de siembra/cosecha', pt: 'Calendário de plantio/colheita', en: 'Planting calendar' },
      prompt: {
        es: '¿Existe calendario de siembra/cosecha por parcela y cultivo, con rotación, o se planta según semilla/mano de obra disponible?',
        pt: 'Existe calendário de plantio/colheita por parcela e cultura, com rotação, ou planta conforme semente/mão de obra disponível?',
        en: 'Is there a parcel/crop planting calendar with rotation, or ad-hoc planting?',
      },
      help: {
        es: 'Evidencia: calendario, mapa de parcelas, rotación 2–3 años',
        pt: 'Evidência: calendário, mapa de parcelas, rotação 2–3 anos',
        en: 'Evidence: calendar, parcel map, 2–3 year rotation',
      },
      level5: {
        es: 'Calendario multi-parcela + rotación documentada + buffer climático',
        pt: 'Calendário multi-parcela + rotação documentada + buffer climático',
        en: 'Multi-parcel calendar + documented rotation + climate buffer',
      },
      pillarSlug: 'operations',
      weight: 1.25,
    },
    {
      id: 'AGR-AGR-02',
      blockId: 'agr',
      blockLabel: { es: 'Agronomía y planificación', pt: 'Agronomia e planeamento', en: 'Agronomy & planning' },
      areaName: { es: 'Variedades y genética', pt: 'Variedades e genética', en: 'Varieties & genetics' },
      prompt: {
        es: '¿Cómo se eligen variedades/semillas y hay registro de lotes y origen?',
        pt: 'Como se escolhem variedades/sementes e há registo de lotes e origem?',
        en: 'How are varieties/seed chosen, and are seed lots/origin recorded?',
      },
      help: {
        es: 'Evidencia: fichas de variedad, proveedores, germinación',
        pt: 'Evidência: fichas de variedade, fornecedores, germinação',
        en: 'Evidence: variety sheets, suppliers, germination',
      },
      level5: {
        es: 'Criterios de selección + rastreo de lotes + ensayo interno mínimo',
        pt: 'Critérios de seleção + rastreio de lotes + ensaio interno mínimo',
        en: 'Selection criteria + lot traceability + minimal internal trial',
      },
      pillarSlug: 'operations',
      weight: 1.1,
    },
    {
      id: 'AGR-AGR-03',
      blockId: 'agr',
      blockLabel: { es: 'Agronomía y planificación', pt: 'Agronomia e planeamento', en: 'Agronomy & planning' },
      areaName: { es: 'Suelo y fertilidad', pt: 'Solo e fertilidade', en: 'Soil & fertility' },
      prompt: {
        es: '¿Hay análisis de suelo periódicos y plan de fertilización por parcela, o abono “igual para todos”?',
        pt: 'Há análises de solo periódicas e plano de fertilização por parcela, ou adubo “igual para todos”?',
        en: 'Are there periodic soil tests and per-parcel fertility plans?',
      },
      help: {
        es: 'Evidencia: laudos, dosis kg/ha, fechas',
        pt: 'Evidência: laudos, doses kg/ha, datas',
        en: 'Evidence: lab reports, kg/ha doses, dates',
      },
      level5: {
        es: 'Análisis ≥1×/año + plan por parcela + reposición de nutrientes',
        pt: 'Análise ≥1×/ano + plano por parcela + reposição de nutrientes',
        en: '≥1 soil test/year + per-parcel plan + nutrient replacement',
      },
      pillarSlug: 'operations',
      weight: 1.2,
    },
    {
      id: 'AGR-AGR-04',
      blockId: 'agr',
      blockLabel: { es: 'Agronomía y planificación', pt: 'Agronomia e planeamento', en: 'Agronomy & planning' },
      areaName: { es: 'Protección de cultivos (MIP)', pt: 'Proteção de cultivos (MIP)', en: 'IPM' },
      prompt: {
        es: '¿Cómo se deciden pulverizaciones (calendario fijo, umbral, técnico) y hay registros de aplicaciones con carencia?',
        pt: 'Como se decidem pulverizações (calendário fixo, limiar, técnico) e há registos de aplicações com carência?',
        en: 'How are sprays decided, and are applications/PHI recorded?',
      },
      help: {
        es: 'Evidencia: cuaderno de campo, recetario, carencias',
        pt: 'Evidência: caderno de campo, receituário, carências',
        en: 'Evidence: field book, prescriptions, PHIs',
      },
      level5: {
        es: 'MIP con umbrales + cuaderno completo + cumplimiento de carencia',
        pt: 'MIP com limiares + caderno completo + cumprimento de carência',
        en: 'Threshold IPM + full field book + PHI compliance',
      },
      pillarSlug: 'risk',
      weight: 1.2,
    },
    {
      id: 'AGR-AGR-05',
      blockId: 'agr',
      blockLabel: { es: 'Agronomía y planificación', pt: 'Agronomia e planeamento', en: 'Agronomy & planning' },
      areaName: { es: 'Irrigación', pt: 'Irrigação', en: 'Irrigation' },
      prompt: {
        es: '¿La irrigación es por turno fijo, observación visual o criterio técnico (tensión/ET/sensores)? ¿Se conocen pérdidas de red?',
        pt: 'A irrigação é por turno fixo, observação visual ou critério técnico (tensão/ET/sensores)? Conhecem perdas na rede?',
        en: 'Is irrigation fixed-shift, visual, or criteria-based, and are network losses known?',
      },
      help: {
        es: 'Evidencia: método, frecuencia, eficiencia estimada',
        pt: 'Evidência: método, frequência, eficiência estimada',
        en: 'Evidence: method, frequency, estimated efficiency',
      },
      level5: {
        es: 'Criterio técnico + eficiencia medida + mantenimiento de red',
        pt: 'Critério técnico + eficiência medida + manutenção de rede',
        en: 'Technical criteria + measured efficiency + network maintenance',
      },
      pillarSlug: 'operations',
      weight: 1.15,
    },
    {
      id: 'AGR-OPE-01',
      blockId: 'ope',
      blockLabel: { es: 'Operaciones de campo y poscosecha', pt: 'Operações de campo e pós-colheita', en: 'Field & postharvest ops' },
      areaName: { es: 'SOPs críticos', pt: 'SOPs críticos', en: 'Critical SOPs' },
      prompt: {
        es: '¿Existen procedimientos/checklists para siembra, pulverización, cosecha y transporte interno, o el saber está solo en personas clave?',
        pt: 'Existem procedimentos/checklists para plantio, pulverização, colheita e transporte interno, ou o saber está só em pessoas-chave?',
        en: 'Are there SOPs/checklists for planting, spraying, harvest and internal haul, or only tacit know-how?',
      },
      help: {
        es: 'Evidencia: checklists, fotos, entrenamiento',
        pt: 'Evidência: checklists, fotos, treino',
        en: 'Evidence: checklists, photos, training',
      },
      level5: {
        es: 'SOPs versionados + checklist por operación + entrenamiento registrado',
        pt: 'SOPs versionados + checklist por operação + treino registado',
        en: 'Versioned SOPs + per-op checklist + recorded training',
      },
      pillarSlug: 'operations',
      weight: 1.2,
    },
    {
      id: 'AGR-OPE-03',
      blockId: 'ope',
      blockLabel: { es: 'Operaciones de campo y poscosecha', pt: 'Operações de campo e pós-colheita', en: 'Field & postharvest ops' },
      areaName: { es: 'Pérdidas en cosecha', pt: 'Perdas na colheita', en: 'Harvest losses' },
      prompt: {
        es: '¿Cómo se estiman pérdidas en cosecha y hay meta/medición, o se “absorben” en el volumen final?',
        pt: 'Como se estimam perdas na colheita e há meta/medição, ou são “absorvidas” no volume final?',
        en: 'How are harvest losses estimated, and is there a measured target?',
      },
      help: {
        es: 'Evidencia: % pérdida, causas, últimos 2 ciclos',
        pt: 'Evidência: % perda, causas, últimos 2 ciclos',
        en: 'Evidence: loss %, causes, last 2 cycles',
      },
      level5: {
        es: 'Medición por parcela + meta < umbral + acciones correctivas',
        pt: 'Medição por parcela + meta < limiar + ações corretivas',
        en: 'Per-parcel measurement + below-threshold target + corrective actions',
      },
      pillarSlug: 'operations',
      weight: 1.25,
    },
    {
      id: 'AGR-OPE-04',
      blockId: 'ope',
      blockLabel: { es: 'Operaciones de campo y poscosecha', pt: 'Operações de campo e pós-colheita', en: 'Field & postharvest ops' },
      areaName: { es: 'Almacenamiento poscosecha', pt: 'Armazenamento pós-colheita', en: 'Postharvest storage' },
      prompt: {
        es: '¿Dónde y cómo se almacena (silo, galpón, frío)? ¿Hay control de humedad, plagas y tiempo hasta venta?',
        pt: 'Onde e como se armazena (silo, galpão, frio)? Há controlo de umidade, pragas e tempo até venda?',
        en: 'Where/how is product stored, and are moisture, pests and time-to-sale controlled?',
      },
      help: {
        es: 'Evidencia: capacidad t, pérdidas en almacén, protocolos',
        pt: 'Evidência: capacidade t, perdas em armazém, protocolos',
        en: 'Evidence: capacity, storage losses, protocols',
      },
      level5: {
        es: 'Protocolo de almacenamiento + monitoreo + pérdidas < meta',
        pt: 'Protocolo de armazenamento + monitorização + perdas < meta',
        en: 'Storage protocol + monitoring + losses below target',
      },
      pillarSlug: 'operations',
      weight: 1.15,
    },
    {
      id: 'AGR-INS-01',
      blockId: 'ins',
      blockLabel: { es: 'Insumos, crédito y trazabilidad', pt: 'Insumos, crédito e rastreabilidade', en: 'Inputs, credit & traceability' },
      areaName: { es: 'Compras de insumos', pt: 'Compras de insumos', en: 'Input purchasing' },
      prompt: {
        es: '¿Las compras de semilla/fertilizante/defensivo son planificadas y negociadas, o emergentes a precio de oportunidad?',
        pt: 'As compras de semente/fertilizante/defensivo são planeadas e negociadas, ou emergenciais a preço de oportunidade?',
        en: 'Are input purchases planned/negotiated, or emergency spot buys?',
      },
      help: {
        es: 'Evidencia: calendario de compra, proveedores, plazos',
        pt: 'Evidência: calendário de compra, fornecedores, prazos',
        en: 'Evidence: purchase calendar, suppliers, terms',
      },
      level5: {
        es: 'Plan de compras + condiciones + comparación de precio unitario',
        pt: 'Plano de compras + condições + comparação de preço unitário',
        en: 'Purchase plan + terms + unit-price comparison',
      },
      pillarSlug: 'finance',
      weight: 1.1,
    },
    {
      id: 'AGR-INS-02',
      blockId: 'ins',
      blockLabel: { es: 'Insumos, crédito y trazabilidad', pt: 'Insumos, crédito e rastreabilidade', en: 'Inputs, credit & traceability' },
      areaName: { es: 'Crédito de ciclo', pt: 'Crédito de ciclo', en: 'Season credit' },
      prompt: {
        es: '¿Cómo se financia el ciclo y cuál es el costo efectivo del dinero si el precio cae?',
        pt: 'Como se financia o ciclo e qual é o custo efetivo do dinheiro se o preço cair?',
        en: 'How is the season financed, and what is effective cost of capital if prices fall?',
      },
      help: {
        es: 'Evidencia: fuentes, tasas, garantías, calendario de pagos',
        pt: 'Evidência: fontes, taxas, garantias, calendário de pagamentos',
        en: 'Evidence: sources, rates, collateral, payment calendar',
      },
      level5: {
        es: 'Mapa de deuda por ciclo + costo efectivo + stress de precio',
        pt: 'Mapa de dívida por ciclo + custo efetivo + stress de preço',
        en: 'Per-cycle debt map + effective cost + price stress',
      },
      pillarSlug: 'finance',
      weight: 1.25,
    },
    {
      id: 'AGR-INS-03',
      blockId: 'ins',
      blockLabel: { es: 'Insumos, crédito y trazabilidad', pt: 'Insumos, crédito e rastreabilidade', en: 'Inputs, credit & traceability' },
      areaName: { es: 'Trazabilidad parcela→lote', pt: 'Rastreabilidade parcela→lote', en: 'Parcel→lot traceability' },
      prompt: {
        es: '¿Se puede vincular un lote cosechado a insumos y prácticas de la parcela (certificación/reclamos)?',
        pt: 'É possível ligar um lote colhido aos insumos e práticas da parcela (certificação/reclamações)?',
        en: 'Can a harvested lot be linked to parcel inputs/practices?',
      },
      help: {
        es: 'Evidencia: cuaderno de campo, códigos de lote',
        pt: 'Evidência: caderno de campo, códigos de lote',
        en: 'Evidence: field book, lot codes',
      },
      level5: {
        es: 'Rastreo parcela→lote→cliente recuperable en <24h',
        pt: 'Rastreio parcela→lote→cliente recuperável em <24h',
        en: 'Parcel→lot→customer trace recoverable in <24h',
      },
      pillarSlug: 'digital',
      weight: 1.15,
    },
    {
      id: 'AGR-COM-01',
      blockId: 'com',
      blockLabel: { es: 'Comercialización y mercados', pt: 'Comercialização e mercados', en: 'Commercialization & markets' },
      areaName: { es: 'Mix de canales', pt: 'Mix de canais', en: 'Channel mix' },
      prompt: {
        es: '¿Cuál es el mix de canales (intermediario, cooperativa, industria, exportación, directo) y margen aproximado por canal?',
        pt: 'Qual é o mix de canais (intermediário, cooperativa, indústria, exportação, direto) e margem aproximada por canal?',
        en: 'What is the channel mix and approximate margin by channel?',
      },
      help: {
        es: 'Evidencia: % volumen y precio neto por canal (último ciclo)',
        pt: 'Evidência: % volume e preço líquido por canal (último ciclo)',
        en: 'Evidence: volume % and net price by channel (last cycle)',
      },
      level5: {
        es: 'Mix medido + margen neto por canal + política de canal',
        pt: 'Mix medido + margem líquida por canal + política de canal',
        en: 'Measured mix + net margin by channel + channel policy',
      },
      pillarSlug: 'commercial',
      weight: 1.2,
    },
    {
      id: 'AGR-COM-02',
      blockId: 'com',
      blockLabel: { es: 'Comercialización y mercados', pt: 'Comercialização e mercados', en: 'Commercialization & markets' },
      areaName: { es: 'Contratos / forward', pt: 'Contratos / forward', en: 'Forward contracts' },
      prompt: {
        es: '¿Hay contratos forward/integración/entrega programada, o la venta es spot en cosecha?',
        pt: 'Há contratos forward/integração/entrega programada, ou a venda é spot na colheita?',
        en: 'Are there forward/integration contracts, or only spot at harvest?',
      },
      help: {
        es: 'Evidencia: contratos, penalidades, cumplimiento histórico',
        pt: 'Evidência: contratos, penalidades, cumprimento histórico',
        en: 'Evidence: contracts, penalties, historical fulfillment',
      },
      level5: {
        es: '% volumen contratado + cumplimiento ≥ meta + gestión de desvío',
        pt: '% volume contratado + cumprimento ≥ meta + gestão de desvio',
        en: 'Contracted volume % + on-target fulfillment + variance management',
      },
      pillarSlug: 'commercial',
      weight: 1.2,
    },
    {
      id: 'AGR-COM-03',
      blockId: 'com',
      blockLabel: { es: 'Comercialización y mercados', pt: 'Comercialização e mercados', en: 'Commercialization & markets' },
      areaName: { es: 'Formación de precio', pt: 'Formação de preço', en: 'Price formation' },
      prompt: {
        es: '¿El precio se acepta del intermediario, se indexa a referencia, o se negocia con costo/ha + margen objetivo?',
        pt: 'O preço é aceito do intermediário, indexado a referência, ou negociado com custo/ha + margem objetivo?',
        en: 'Is price take-it-or-leave-it, index-linked, or cost/ha + target margin?',
      },
      help: {
        es: 'Evidencia: referencias de precio, timing de venta',
        pt: 'Evidência: referências de preço, timing de venda',
        en: 'Evidence: price refs, sale timing',
      },
      level5: {
        es: 'Precio anclado en costo+margen y/o contrato con reglas claras',
        pt: 'Preço ancorado em custo+margem e/ou contrato com regras claras',
        en: 'Price anchored on cost+margin and/or clear contract rules',
      },
      pillarSlug: 'commercial',
      weight: 1.15,
    },
    {
      id: 'AGR-FIN-01',
      blockId: 'fin',
      blockLabel: { es: 'Finanzas y costo por hectárea', pt: 'Finanças e custo por hectare', en: 'Finance & cost per hectare' },
      areaName: { es: 'Segregación de caja', pt: 'Segregação de caixa', en: 'Cash segregation' },
      prompt: {
        es: '¿El flujo de caja agrícola está separado del doméstico/otras actividades? ¿Se ve resultado por cultivo o parcela?',
        pt: 'O fluxo de caixa agrícola está separado do doméstico/outras atividades? Vê-se resultado por cultura ou parcela?',
        en: 'Is farm cash separated from household/other activities, with P&L by crop/parcel?',
      },
      help: {
        es: 'Evidencia: cuentas, centros de costo, P&L simple',
        pt: 'Evidência: contas, centros de custo, P&L simples',
        en: 'Evidence: accounts, cost centers, simple P&L',
      },
      level5: {
        es: 'Centros de costo por cultivo/parcela + P&L por ciclo',
        pt: 'Centros de custo por cultura/parcela + P&L por ciclo',
        en: 'Cost centers by crop/parcel + cycle P&L',
      },
      pillarSlug: 'finance',
      weight: 1.3,
    },
    {
      id: 'AGR-FIN-02',
      blockId: 'fin',
      blockLabel: { es: 'Finanzas y costo por hectárea', pt: 'Finanças e custo por hectare', en: 'Finance & cost per hectare' },
      areaName: { es: 'Costo por hectárea', pt: 'Custo por hectare', en: 'Cost per hectare' },
      prompt: {
        es: '¿Existe cálculo de costo/ha (insumos, mano de obra, máquina, agua, tierra, financiero) actualizado por ciclo?',
        pt: 'Existe cálculo de custo/ha (insumos, mão de obra, máquina, água, terra, financeiro) atualizado por ciclo?',
        en: 'Is cost/ha (inputs, labor, machine, water, land, finance) updated each cycle?',
      },
      help: {
        es: 'Evidencia: planilla de costo, últimos 2 ciclos',
        pt: 'Evidência: planilha de custo, últimos 2 ciclos',
        en: 'Evidence: cost sheet, last 2 cycles',
      },
      level5: {
        es: 'Costo/ha estandarizado + actualización por ciclo + benchmark interno',
        pt: 'Custo/ha padronizado + atualização por ciclo + benchmark interno',
        en: 'Standard cost/ha + cycle updates + internal benchmark',
      },
      pillarSlug: 'finance',
      weight: 1.35,
    },
    {
      id: 'AGR-FIN-03',
      blockId: 'fin',
      blockLabel: { es: 'Finanzas y costo por hectárea', pt: 'Finanças e custo por hectare', en: 'Finance & cost per hectare' },
      areaName: { es: 'Rendimiento y margen/ha', pt: 'Rendimento e margem/ha', en: 'Yield & margin/ha' },
      prompt: {
        es: '¿Conocen rendimiento (t/ha) y margen de contribución por cultivo después de variables? ¿Qué cultivo realmente paga la tierra?',
        pt: 'Conhecem rendimento (t/ha) e margem de contribuição por cultura após variáveis? Que cultura realmente paga a terra?',
        en: 'Do you know yield (t/ha) and contribution margin by crop after variables?',
      },
      help: {
        es: 'Evidencia: t/ha, ingreso neto, margen',
        pt: 'Evidência: t/ha, receita líquida, margem',
        en: 'Evidence: t/ha, net revenue, margin',
      },
      level5: {
        es: 'Margen por cultivo + decisión de portafolio basada en ello',
        pt: 'Margem por cultura + decisão de portfólio baseada nisso',
        en: 'Margin by crop + portfolio decisions based on it',
      },
      pillarSlug: 'finance',
      weight: 1.3,
    },
    {
      id: 'AGR-FIN-04',
      blockId: 'fin',
      blockLabel: { es: 'Finanzas y costo por hectárea', pt: 'Finanças e custo por hectare', en: 'Finance & cost per hectare' },
      areaName: { es: 'Punto de equilibrio', pt: 'Ponto de equilíbrio', en: 'Break-even' },
      prompt: {
        es: '¿Saben el volumen/precio mínimo para cubrir fijos+deuda del ciclo y hay reserva de liquidez?',
        pt: 'Sabem o volume/preço mínimo para cobrir fixos+dívida do ciclo e há reserva de liquidez?',
        en: 'Do you know break-even volume/price for cycle fixed+debt costs, with a cash buffer?',
      },
      help: {
        es: 'Evidencia: break-even, meses de caja, stress test',
        pt: 'Evidência: break-even, meses de caixa, stress test',
        en: 'Evidence: break-even, months of cash, stress test',
      },
      level5: {
        es: 'Break-even por cultivo + buffer de liquidez definido',
        pt: 'Break-even por cultura + buffer de liquidez definido',
        en: 'Break-even by crop + defined liquidity buffer',
      },
      pillarSlug: 'finance',
      weight: 1.25,
    },
    {
      id: 'AGR-PEO-01',
      blockId: 'peo',
      blockLabel: { es: 'Personas, riesgo y escalabilidad', pt: 'Pessoas, risco e escalabilidade', en: 'People, risk & scale' },
      areaName: { es: 'Mano de obra estacional', pt: 'Mão de obra sazonal', en: 'Seasonal labor' },
      prompt: {
        es: '¿Cómo se cubre el pico de cosecha y hay escasez recurrente con impacto en pérdidas por atraso?',
        pt: 'Como se cobre o pico de colheita e há escassez recorrente com impacto em perdas por atraso?',
        en: 'How is harvest peak staffed, and does recurrent scarcity drive delay losses?',
      },
      help: {
        es: 'Evidencia: dotación, faltas, atraso de cosecha',
        pt: 'Evidência: dotação, faltas, atraso de colheita',
        en: 'Evidence: staffing, absences, harvest delay',
      },
      level5: {
        es: 'Plan de mano de obra estacional + cobertura ≥ meta de ventana',
        pt: 'Plano de mão de obra sazonal + cobertura ≥ meta de janela',
        en: 'Seasonal labor plan + window coverage on target',
      },
      pillarSlug: 'people',
      weight: 1.15,
    },
    {
      id: 'AGR-RSK-01',
      blockId: 'peo',
      blockLabel: { es: 'Personas, riesgo y escalabilidad', pt: 'Pessoas, risco e escalabilidade', en: 'People, risk & scale' },
      areaName: { es: 'Riesgo climático y seguros', pt: 'Risco climático e seguros', en: 'Climate risk & insurance' },
      prompt: {
        es: '¿Qué riesgos climáticos/plagas impactaron los últimos 3 ciclos y hay seguro o mitigación explícita?',
        pt: 'Que riscos climáticos/pragas impactaram os últimos 3 ciclos e há seguro ou mitigação explícita?',
        en: 'Which climate/pest risks hit the last 3 cycles, and is there insurance or explicit mitigation?',
      },
      help: {
        es: 'Evidencia: historial de pérdidas, pólizas, medidas',
        pt: 'Evidência: histórico de perdas, apólices, medidas',
        en: 'Evidence: loss history, policies, measures',
      },
      level5: {
        es: 'Mapa de riesgos + mitigación + seguro donde aplique',
        pt: 'Mapa de riscos + mitigação + seguro onde fizer sentido',
        en: 'Risk map + mitigation + insurance where relevant',
      },
      pillarSlug: 'risk',
      weight: 1.2,
    },
    {
      id: 'AGR-EXP-01',
      blockId: 'peo',
      blockLabel: { es: 'Personas, riesgo y escalabilidad', pt: 'Pessoas, risco e escalabilidade', en: 'People, risk & scale' },
      areaName: { es: 'Dependencia del productor', pt: 'Dependência do produtor', en: 'Producer dependency' },
      prompt: {
        es: '¿La operación aguanta 30 días sin el productor en el campo? ¿Qué se rompe primero?',
        pt: 'A operação aguenta 30 dias sem o produtor no campo? O que quebra primeiro?',
        en: 'Can operations run 30 days without the producer on-site? What breaks first?',
      },
      help: {
        es: 'Evidencia: prueba real/hipotética, roles backup',
        pt: 'Evidência: teste real/hipotético, papéis backup',
        en: 'Evidence: real/hypothetical test, backup roles',
      },
      level5: {
        es: 'Operación 30 días con backup documentado en procesos críticos',
        pt: 'Operação 30 dias com backup documentado nos processos críticos',
        en: '30-day operation with documented backup on critical processes',
      },
      pillarSlug: 'people',
      weight: 1.2,
    },
    {
      id: 'AGR-EXP-02',
      blockId: 'peo',
      blockLabel: { es: 'Personas, riesgo y escalabilidad', pt: 'Pessoas, risco e escalabilidade', en: 'People, risk & scale' },
      areaName: { es: 'Datos y digitalización', pt: 'Dados e digitalização', en: 'Data & digitization' },
      prompt: {
        es: '¿Qué datos existen en digital (área, costos, ventas, aplicaciones) frente a solo memoria/cuaderno?',
        pt: 'Que dados existem em digital (área, custos, vendas, aplicações) frente a só memória/caderno?',
        en: 'What data exists digitally (area, costs, sales, sprays) vs memory/notebook only?',
      },
      help: {
        es: 'Evidencia: herramientas, campos llenados, frecuencia',
        pt: 'Evidência: ferramentas, campos preenchidos, frequência',
        en: 'Evidence: tools, filled fields, frequency',
      },
      level5: {
        es: 'Núcleo digital mínimo (parcelas, costos, ventas, cuaderno) actualizado en el ciclo',
        pt: 'Núcleo digital mínimo (parcelas, custos, vendas, caderno) atualizado no ciclo',
        en: 'Minimal digital core (parcels, costs, sales, field book) updated each cycle',
      },
      pillarSlug: 'digital',
      weight: 1.1,
    },
  ],
};
