import type { SectorMatrix } from './types';

/** Matriz profunda agroindústria — proposta v0 (co-construção). */
export const AGROINDUSTRY_MATRIX: SectorMatrix = {
  sectorId: 'agroindustry',
  items: [
    {
      id: 'AIN-GOB-01',
      blockId: 'gob',
      blockLabel: { es: 'Gobernanza y modelo industrial', pt: 'Governança e modelo industrial', en: 'Industrial governance' },
      areaName: { es: 'Entidad y patrimonio', pt: 'Entidade e património', en: 'Entity & assets' },
      prompt: {
        es: '¿La agroindustria opera con segregación clara entre patrimonio personal e industrial? ¿Cuántas razones sociales comparten la misma caja?',
        pt: 'A agroindústria opera com segregação clara entre património pessoal e industrial? Quantas razões sociais partilham a mesma caixa?',
        en: 'Is personal vs industrial wealth segregated, and how many legal entities share one cash pool?',
      },
      help: {
        es: 'Evidencia: razones sociales, cuentas, mezcla de flujos',
        pt: 'Evidência: razões sociais, contas, mistura de fluxos',
        en: 'Evidence: legal entities, accounts, mixed cash flows',
      },
      level5: {
        es: 'Entidad económica separada + P&L industrial auditable',
        pt: 'Entidade económica separada + P&L industrial auditável',
        en: 'Separate economic entity + auditable industrial P&L',
      },
      pillarSlug: 'risk',
      weight: 1.3,
    },
    {
      id: 'AIN-GOB-02',
      blockId: 'gob',
      blockLabel: { es: 'Gobernanza y modelo industrial', pt: 'Governança e modelo industrial', en: 'Industrial governance' },
      areaName: { es: 'Plan 12–24 meses', pt: 'Plano 12–24 meses', en: '12–24 month plan' },
      prompt: {
        es: '¿Existe plan de volúmenes, mix, CAPEX y certificaciones a 12–24 meses, o la planta solo reacciona a pedidos y liquidez?',
        pt: 'Existe plano de volumes, mix, CAPEX e certificações a 12–24 meses, ou a planta só reage a pedidos e liquidez?',
        en: 'Is there a 12–24m volume/mix/CAPEX/cert plan, or only order/liquidity reaction?',
      },
      help: {
        es: 'Evidencia: plan escrito, metas de tonelaje/SKU',
        pt: 'Evidência: plano escrito, metas de tonelagem/SKU',
        en: 'Evidence: written plan, tonnage/SKU goals',
      },
      level5: {
        es: 'Plan con OKRs, revisión trimestral y escenarios de demanda/precio',
        pt: 'Plano com OKRs, revisão trimestral e cenários de procura/preço',
        en: 'OKR plan, quarterly review, demand/price scenarios',
      },
      pillarSlug: 'strategy',
      weight: 1.25,
    },
    {
      id: 'AIN-GOB-03',
      blockId: 'gob',
      blockLabel: { es: 'Gobernanza y modelo industrial', pt: 'Governança e modelo industrial', en: 'Industrial governance' },
      areaName: { es: 'Portafolio de SKUs', pt: 'Portfólio de SKUs', en: 'SKU portfolio' },
      prompt: {
        es: '¿Cuántos SKUs activos hay y cuáles son estrella / vaca / peso muerto en margen y complejidad?',
        pt: 'Quantos SKUs ativos existem e quais são estrela / vaca / peso morto em margem e complexidade?',
        en: 'How many active SKUs, and which are stars/cash-cows/dogs on margin vs complexity?',
      },
      help: {
        es: 'Evidencia: lista SKU, margen, % volumen',
        pt: 'Evidência: lista SKU, margem, % volume',
        en: 'Evidence: SKU list, margin, volume %',
      },
      level5: {
        es: 'Matriz de portafolio con decisión de descontinuar/invertir',
        pt: 'Matriz de portfólio com decisão de descontinuar/investir',
        en: 'Portfolio matrix with kill/invest decisions',
      },
      pillarSlug: 'commercial',
      weight: 1.15,
    },
    {
      id: 'AIN-GOB-04',
      blockId: 'gob',
      blockLabel: { es: 'Gobernanza y modelo industrial', pt: 'Governança e modelo industrial', en: 'Industrial governance' },
      areaName: { es: 'Línea media / turnos', pt: 'Linha média / turnos', en: 'Middle management / shifts' },
      prompt: {
        es: '¿La planta funciona un turno completo sin el dueño en el piso? ¿Hay supervisor con autoridad formal?',
        pt: 'A planta funciona um turno completo sem o dono no chão? Existe supervisor com autoridade formal?',
        en: 'Can a full shift run without the owner on the floor, with a formal supervisor?',
      },
      help: {
        es: 'Evidencia: organigrama, turnos, quién autoriza paradas',
        pt: 'Evidência: organigrama, turnos, quem autoriza paragens',
        en: 'Evidence: org chart, shifts, who authorizes stops',
      },
      level5: {
        es: 'Línea media con JD + autonomía documentada',
        pt: 'Linha média com JD + autonomia documentada',
        en: 'Middle line with JDs + documented autonomy',
      },
      pillarSlug: 'people',
      weight: 1.2,
    },
    {
      id: 'AIN-CAP-01',
      blockId: 'cap',
      blockLabel: { es: 'Capacidad y proceso', pt: 'Capacidade e processo', en: 'Capacity & process' },
      areaName: { es: 'Capacidad vs. utilización', pt: 'Capacidade vs. utilização', en: 'Capacity vs utilization' },
      prompt: {
        es: '¿Cuál es la capacidad nominal (t/turno o und/h) y la utilización real? ¿Dónde está el cuello de botella?',
        pt: 'Qual é a capacidade nominal (t/turno ou und/h) e a utilização real? Onde está o gargalo?',
        en: 'What is nominal capacity vs real utilization, and where is the bottleneck?',
      },
      help: {
        es: 'Evidencia: capacidad, OEE aproximado, gargalo',
        pt: 'Evidência: capacidade, OEE aproximado, gargalo',
        en: 'Evidence: capacity, approx OEE, bottleneck',
      },
      level5: {
        es: 'Capacidad y utilización medidas + gargalo con plan',
        pt: 'Capacidade e utilização medidas + gargalo com plano',
        en: 'Measured capacity/utilization + bottleneck plan',
      },
      pillarSlug: 'operations',
      weight: 1.3,
    },
    {
      id: 'AIN-CAP-02',
      blockId: 'cap',
      blockLabel: { es: 'Capacidad y proceso', pt: 'Capacidade e processo', en: 'Capacity & process' },
      areaName: { es: 'Fichas técnicas / BOM', pt: 'Fichas técnicas / BOM', en: 'Tech sheets / BOM' },
      prompt: {
        es: '¿Cada producto tiene ficha técnica/BOM con gramajes y rendimientos esperados, o la receta está “en la cabeza”?',
        pt: 'Cada produto tem ficha técnica/BOM com gramagens e rendimentos esperados, ou a receita está “na cabeça”?',
        en: 'Does each product have a BOM with weights/yields, or is the recipe tacit?',
      },
      help: {
        es: 'Evidencia: fichas, balanzas, desvíos',
        pt: 'Evidência: fichas, balanças, desvios',
        en: 'Evidence: sheets, scales, variances',
      },
      level5: {
        es: 'BOM versionado + gramaje obligatorio + rendimiento estándar',
        pt: 'BOM versionado + gramagem obrigatória + rendimento padrão',
        en: 'Versioned BOM + mandatory weighing + standard yield',
      },
      pillarSlug: 'operations',
      weight: 1.35,
    },
    {
      id: 'AIN-CAP-05',
      blockId: 'cap',
      blockLabel: { es: 'Capacidad y proceso', pt: 'Capacidade e processo', en: 'Capacity & process' },
      areaName: { es: 'Rendimiento y mermas', pt: 'Rendimento e mermas', en: 'Yield & waste' },
      prompt: {
        es: '¿Conocen rendimiento (MP→PA) y % merma por causa (aparas, quiebres, reproceso, vencidos)?',
        pt: 'Conhecem rendimento (MP→PA) e % merma por causa (aparas, quebras, reprocesso, expirados)?',
        en: 'Do you know MP→FG yield and waste % by cause?',
      },
      help: {
        es: 'Evidencia: % rendimiento, causas, últimos 3 meses',
        pt: 'Evidência: % rendimento, causas, últimos 3 meses',
        en: 'Evidence: yield %, causes, last 3 months',
      },
      level5: {
        es: 'Rendimiento por SKU + merma < meta + Pareto de causas',
        pt: 'Rendimento por SKU + merma < meta + Pareto de causas',
        en: 'Yield by SKU + waste below target + cause Pareto',
      },
      pillarSlug: 'operations',
      weight: 1.3,
    },
    {
      id: 'AIN-CAP-04',
      blockId: 'cap',
      blockLabel: { es: 'Capacidad y proceso', pt: 'Capacidade e processo', en: 'Capacity & process' },
      areaName: { es: 'Mantenimiento', pt: 'Manutenção', en: 'Maintenance' },
      prompt: {
        es: '¿Hay plan de mantenimiento preventivo (frío, cocción, sellado) o solo reparación reactiva que para la línea?',
        pt: 'Há plano de manutenção preventiva (frio, cocção, selagem) ou só reparo reativo que para a linha?',
        en: 'Is there preventive maintenance (cold, cook, seal) or only reactive line-stopping repair?',
      },
      help: {
        es: 'Evidencia: historial de paradas, contratos técnicos',
        pt: 'Evidência: histórico de paragens, contratos técnicos',
        en: 'Evidence: downtime history, service contracts',
      },
      level5: {
        es: 'Preventiva calendarizada + MTBF/MTTR básicos registrados',
        pt: 'Preventiva calendarizada + MTBF/MTTR básicos registados',
        en: 'Scheduled PM + basic MTBF/MTTR logged',
      },
      pillarSlug: 'operations',
      weight: 1.15,
    },
    {
      id: 'AIN-QUA-01',
      blockId: 'qua',
      blockLabel: { es: 'Calidad e inocuidad', pt: 'Qualidade e inocuidade', en: 'Quality & food safety' },
      areaName: { es: 'BPM / higiene', pt: 'BPM / higiene', en: 'GMP / hygiene' },
      prompt: {
        es: '¿Existen checklists diarios de higiene y zonas limpias/sucias respetadas, o protocolos “existen pero no se usan”?',
        pt: 'Existem checklists diários de higiene e zonas limpas/sujas respeitadas, ou protocolos “existem mas não se usam”?',
        en: 'Are daily hygiene checklists and clean/dirty zones actually used?',
      },
      help: {
        es: 'Evidencia: checklists llenados, auditorías',
        pt: 'Evidência: checklists preenchidos, auditorias',
        en: 'Evidence: filled checklists, audits',
      },
      level5: {
        es: 'BPM operacional diario + auditoría interna mensual',
        pt: 'BPM operacional diário + auditoria interna mensal',
        en: 'Daily operational GMP + monthly internal audit',
      },
      pillarSlug: 'risk',
      weight: 1.3,
    },
    {
      id: 'AIN-QUA-02',
      blockId: 'qua',
      blockLabel: { es: 'Calidad e inocuidad', pt: 'Qualidade e inocuidade', en: 'Quality & food safety' },
      areaName: { es: 'HACCP / APPCC', pt: 'HACCP / APPCC', en: 'HACCP' },
      prompt: {
        es: '¿Hay análisis de peligros y CCPs definidos con registros, o solo discurso de inocuidad?',
        pt: 'Há análise de perigos e CCPs definidos com registos, ou só discurso de inocuidade?',
        en: 'Is there a live hazard analysis with recorded CCPs, or only food-safety talk?',
      },
      help: {
        es: 'Evidencia: plan HACCP, registros CCP',
        pt: 'Evidência: plano HACCP, registos CCP',
        en: 'Evidence: HACCP plan, CCP records',
      },
      level5: {
        es: 'HACCP vivo con CCPs registrados y desviaciones tratadas',
        pt: 'HACCP vivo com CCPs registados e desvios tratados',
        en: 'Living HACCP with logged CCPs and handled deviations',
      },
      pillarSlug: 'risk',
      weight: 1.35,
    },
    {
      id: 'AIN-QUA-03',
      blockId: 'qua',
      blockLabel: { es: 'Calidad e inocuidad', pt: 'Qualidade e inocuidade', en: 'Quality & food safety' },
      areaName: { es: 'Trazabilidad y recall', pt: 'Rastreabilidade e recall', en: 'Traceability & recall' },
      prompt: {
        es: '¿Pueden en <4h decir qué lotes de MP entraron a un lote de PA y a qué clientes fueron? ¿Simularon recall?',
        pt: 'Conseguem em <4h dizer que lotes de MP entraram num lote de PA e a que clientes foram? Já simularam recall?',
        en: 'Can you map MP lots → FG lot → customers in <4h, and have you simulated recall?',
      },
      help: {
        es: 'Evidencia: prueba de rastreo, códigos de lote',
        pt: 'Evidência: teste de rastreio, códigos de lote',
        en: 'Evidence: trace test, lot codes',
      },
      level5: {
        es: 'Rastreo MP↔PA↔cliente + simulacro de recall documentado',
        pt: 'Rastreio MP↔PA↔cliente + simulacro de recall documentado',
        en: 'MP↔FG↔customer trace + documented recall drill',
      },
      pillarSlug: 'risk',
      weight: 1.35,
    },
    {
      id: 'AIN-QUA-05',
      blockId: 'qua',
      blockLabel: { es: 'Calidad e inocuidad', pt: 'Qualidade e inocuidade', en: 'Quality & food safety' },
      areaName: { es: 'Rotulado y regulación', pt: 'Rotulagem e regulamentação', en: 'Labeling & regulation' },
      prompt: {
        es: '¿Los rótulos cumplen norma local y quién valida cambios de fórmula vs. rótulo?',
        pt: 'Os rótulos cumprem norma local e quem valida mudanças de fórmula vs. rótulo?',
        en: 'Do labels meet local rules, and who validates formula vs label changes?',
      },
      help: {
        es: 'Evidencia: rótulos, actas de cambio',
        pt: 'Evidência: rótulos, atas de mudança',
        en: 'Evidence: labels, change minutes',
      },
      level5: {
        es: 'Control de cambio fórmula↔rótulo + conformidad auditable',
        pt: 'Controlo de mudança fórmula↔rótulo + conformidade auditável',
        en: 'Formula↔label change control + auditable compliance',
      },
      pillarSlug: 'risk',
      weight: 1.15,
    },
    {
      id: 'AIN-FIN-01',
      blockId: 'fin',
      blockLabel: { es: 'Costeo y control de gestión', pt: 'Costeo e controlo de gestão', en: 'Costing & management control' },
      areaName: { es: 'Centros de costo', pt: 'Centros de custo', en: 'Cost centers' },
      prompt: {
        es: '¿Existe P&L/contribución por línea/turno/cliente grande, o una caja única que esconde líneas deficitarias?',
        pt: 'Existe P&L/contribuição por linha/turno/cliente grande, ou uma caixa única que esconde linhas deficitárias?',
        en: 'Is there P&L/contribution by line/shift/key customer, or one cash pool hiding loss-makers?',
      },
      help: {
        es: 'Evidencia: centros de costo, prorrateos',
        pt: 'Evidência: centros de custo, rateios',
        en: 'Evidence: cost centers, allocations',
      },
      level5: {
        es: 'P&L mensual por línea crítica + prorrateo explícito',
        pt: 'P&L mensal por linha crítica + rateio explícito',
        en: 'Monthly P&L by critical line + explicit allocation',
      },
      pillarSlug: 'finance',
      weight: 1.3,
    },
    {
      id: 'AIN-FIN-02',
      blockId: 'fin',
      blockLabel: { es: 'Costeo y control de gestión', pt: 'Costeo e controlo de gestão', en: 'Costing & management control' },
      areaName: { es: 'Costo estándar vs. real', pt: 'Custo padrão vs. real', en: 'Standard vs actual cost' },
      prompt: {
        es: '¿Hay costo estándar por SKU (MP+MO+pack+energía) comparado al real mensual con dueño de desvíos?',
        pt: 'Há custo padrão por SKU (MP+MO+pack+energia) comparado ao real mensal com dono dos desvios?',
        en: 'Is there standard cost per SKU vs monthly actual with variance owners?',
      },
      help: {
        es: 'Evidencia: ficha de costo, desvíos',
        pt: 'Evidência: ficha de custo, desvios',
        en: 'Evidence: cost sheet, variances',
      },
      level5: {
        es: 'Costo estándar + análisis mensual de desvío con acciones',
        pt: 'Custo padrão + análise mensal de desvio com ações',
        en: 'Standard cost + monthly variance analysis with actions',
      },
      pillarSlug: 'finance',
      weight: 1.35,
    },
    {
      id: 'AIN-FIN-03',
      blockId: 'fin',
      blockLabel: { es: 'Costeo y control de gestión', pt: 'Costeo e controlo de gestão', en: 'Costing & management control' },
      areaName: { es: 'Pricing y margen', pt: 'Pricing e margem', en: 'Pricing & margin' },
      prompt: {
        es: '¿El precio B2B se ancla en margen objetivo o en “lo que el comprador acepta” sin costo?',
        pt: 'O preço B2B ancora-se em margem objetivo ou em “o que o comprador aceita” sem custo?',
        en: 'Is B2B price anchored on target margin or buyer-accepts-it without cost?',
      },
      help: {
        es: 'Evidencia: política de precio, descuentos',
        pt: 'Evidência: política de preço, descontos',
        en: 'Evidence: pricing policy, discounts',
      },
      level5: {
        es: 'Precio = costo+margen objetivo + gobernanza de descuentos',
        pt: 'Preço = custo+margem alvo + governação de descontos',
        en: 'Price = cost+target margin + discount governance',
      },
      pillarSlug: 'finance',
      weight: 1.2,
    },
    {
      id: 'AIN-FIN-04',
      blockId: 'fin',
      blockLabel: { es: 'Costeo y control de gestión', pt: 'Costeo e controlo de gestão', en: 'Costing & management control' },
      areaName: { es: 'Punto de equilibrio planta', pt: 'Ponto de equilíbrio da planta', en: 'Plant break-even' },
      prompt: {
        es: '¿Saben el volumen mínimo mensual (u horas de línea) para cubrir fijos + deuda y lo monitorean?',
        pt: 'Sabem o volume mínimo mensal (ou horas de linha) para cobrir fixos + dívida e monitorizam isso?',
        en: 'Do you know monthly min volume/line-hours to cover fixed+debt, and monitor it?',
      },
      help: {
        es: 'Evidencia: break-even, ocupación',
        pt: 'Evidência: break-even, ocupação',
        en: 'Evidence: break-even, utilization',
      },
      level5: {
        es: 'Break-even actualizado + alerta si 2 meses < 90%',
        pt: 'Break-even atualizado + alerta se 2 meses < 90%',
        en: 'Updated break-even + alert if 2 months < 90%',
      },
      pillarSlug: 'finance',
      weight: 1.25,
    },
    {
      id: 'AIN-COM-01',
      blockId: 'com',
      blockLabel: { es: 'Comercial B2B y servicio', pt: 'Comercial B2B e serviço', en: 'B2B commercial & service' },
      areaName: { es: 'Concentración de clientes', pt: 'Concentração de clientes', en: 'Customer concentration' },
      prompt: {
        es: '¿Qué % de ingresos está en los top 3 clientes y qué pasa si uno cae?',
        pt: 'Que % da receita está nos top 3 clientes e o que acontece se um cair?',
        en: 'What % of revenue is in top 3 customers, and what if one drops?',
      },
      help: {
        es: 'Evidencia: % ingresos, contratos',
        pt: 'Evidência: % receita, contratos',
        en: 'Evidence: revenue %, contracts',
      },
      level5: {
        es: 'Concentración gestionada + pipeline activo + contratos marco',
        pt: 'Concentração gerida + pipeline ativo + contratos-quadro',
        en: 'Managed concentration + active pipeline + frame contracts',
      },
      pillarSlug: 'commercial',
      weight: 1.2,
    },
    {
      id: 'AIN-COM-02',
      blockId: 'com',
      blockLabel: { es: 'Comercial B2B y servicio', pt: 'Comercial B2B e serviço', en: 'B2B commercial & service' },
      areaName: { es: 'OTIF y reclamos', pt: 'OTIF e reclamações', en: 'OTIF & complaints' },
      prompt: {
        es: '¿Miden On-Time In-Full y tasa de reclamos/devoluciones con causas?',
        pt: 'Medem On-Time In-Full e taxa de reclamações/devoluções com causas?',
        en: 'Do you measure OTIF and complaint/return rates with causes?',
      },
      help: {
        es: 'Evidencia: % OTIF, devoluciones',
        pt: 'Evidência: % OTIF, devoluções',
        en: 'Evidence: OTIF %, returns',
      },
      level5: {
        es: 'OTIF ≥ meta + Pareto de reclamos con dueño',
        pt: 'OTIF ≥ meta + Pareto de reclamações com dono',
        en: 'OTIF on target + complaint Pareto with owners',
      },
      pillarSlug: 'commercial',
      weight: 1.25,
    },
    {
      id: 'AIN-COM-04',
      blockId: 'com',
      blockLabel: { es: 'Comercial B2B y servicio', pt: 'Comercial B2B e serviço', en: 'B2B commercial & service' },
      areaName: { es: 'S&OP / forecast', pt: 'S&OP / forecast', en: 'S&OP / forecast' },
      prompt: {
        es: '¿La producción planea con forecast o solo con pedidos de la semana? ¿Hay S&OP mínimo ventas×producción×compras?',
        pt: 'A produção planeia com forecast ou só com pedidos da semana? Há S&OP mínimo vendas×produção×compras?',
        en: 'Does production plan with forecast or only weekly orders? Is there a minimal S&OP?',
      },
      help: {
        es: 'Evidencia: forecast, actas',
        pt: 'Evidência: forecast, atas',
        en: 'Evidence: forecast, minutes',
      },
      level5: {
        es: 'Ciclo S&OP mensual con forecast y capacidad',
        pt: 'Ciclo S&OP mensal com forecast e capacidade',
        en: 'Monthly S&OP with forecast and capacity',
      },
      pillarSlug: 'strategy',
      weight: 1.15,
    },
    {
      id: 'AIN-LOG-01',
      blockId: 'log',
      blockLabel: { es: 'Supply chain y logística', pt: 'Supply chain e logística', en: 'Supply chain & logistics' },
      areaName: { es: 'Recepción de MP', pt: 'Receção de MP', en: 'Raw material intake' },
      prompt: {
        es: '¿Hay criterios de aceptación en recepción (temp, humedad, defectos, docs) con rechazo formal?',
        pt: 'Há critérios de aceitação na receção (temp, umidade, defeitos, docs) com rejeição formal?',
        en: 'Are there intake acceptance criteria with formal rejection?',
      },
      help: {
        es: 'Evidencia: registros de recepción, rechazos',
        pt: 'Evidência: registos de receção, rejeições',
        en: 'Evidence: intake logs, rejections',
      },
      level5: {
        es: 'CQ en recepción + rechazo documentado + feedback a proveedor',
        pt: 'CQ na receção + rejeição documentada + feedback a fornecedor',
        en: 'Intake QC + documented rejection + supplier feedback',
      },
      pillarSlug: 'operations',
      weight: 1.2,
    },
    {
      id: 'AIN-LOG-02',
      blockId: 'log',
      blockLabel: { es: 'Supply chain y logística', pt: 'Supply chain e logística', en: 'Supply chain & logistics' },
      areaName: { es: 'FIFO/FEFO', pt: 'FIFO/FEFO', en: 'FIFO/FEFO' },
      prompt: {
        es: '¿El stock sigue FIFO/FEFO de forma auditable con control de condiciones?',
        pt: 'O stock segue FIFO/FEFO de forma auditável com controlo de condições?',
        en: 'Is stock on auditable FIFO/FEFO with condition control?',
      },
      help: {
        es: 'Evidencia: layout de almacén, pérdidas por caducidad',
        pt: 'Evidência: layout de armazém, perdas por validade',
        en: 'Evidence: warehouse layout, expiry losses',
      },
      level5: {
        es: 'FEFO auditable + condiciones monitoreadas',
        pt: 'FEFO auditável + condições monitorizadas',
        en: 'Auditable FEFO + monitored conditions',
      },
      pillarSlug: 'operations',
      weight: 1.15,
    },
    {
      id: 'AIN-LOG-03',
      blockId: 'log',
      blockLabel: { es: 'Supply chain y logística', pt: 'Supply chain e logística', en: 'Supply chain & logistics' },
      areaName: { es: 'Cadena de frío', pt: 'Cadeia de frio', en: 'Cold chain' },
      prompt: {
        es: 'Si aplica: ¿la cadena de frío es continua planta→transporte→cliente con registros?',
        pt: 'Se aplicável: a cadeia de frio é contínua planta→transporte→cliente com registos?',
        en: 'If applicable: is cold chain continuous plant→transport→customer with logs?',
      },
      help: {
        es: 'Evidencia: dataloggers, quiebres de frío',
        pt: 'Evidência: dataloggers, quebras de frio',
        en: 'Evidence: dataloggers, cold breaks',
      },
      level5: {
        es: 'Frío continuo con registro y alerta de desvío',
        pt: 'Frio contínuo com registo e alerta de desvio',
        en: 'Continuous cold with logging and deviation alerts',
      },
      pillarSlug: 'operations',
      weight: 1.2,
    },
    {
      id: 'AIN-PEO-02',
      blockId: 'peo',
      blockLabel: { es: 'Personas, tecnología y escala', pt: 'Pessoas, tecnologia e escala', en: 'People, tech & scale' },
      areaName: { es: 'Onboarding y polivalencia', pt: 'Onboarding e polivalência', en: 'Onboarding & multi-skilling' },
      prompt: {
        es: '¿Un operador nuevo tiene inducción estructurada o aprende “al lado del antiguo”? ¿Hay matriz de polivalencia?',
        pt: 'Um operador novo tem indução estruturada ou aprende “ao lado do antigo”? Há matriz de polivalência?',
        en: 'Is new-hire induction structured, and is there a multi-skill matrix?',
      },
      help: {
        es: 'Evidencia: manual de inducción, matriz de skills',
        pt: 'Evidência: manual de indução, matriz de skills',
        en: 'Evidence: induction manual, skill matrix',
      },
      level5: {
        es: 'Inducción formal + matriz de polivalencia ≥ cobertura mínima',
        pt: 'Indução formal + matriz de polivalência ≥ cobertura mínima',
        en: 'Formal induction + multi-skill matrix at min coverage',
      },
      pillarSlug: 'people',
      weight: 1.15,
    },
    {
      id: 'AIN-TEC-01',
      blockId: 'peo',
      blockLabel: { es: 'Personas, tecnología y escala', pt: 'Pessoas, tecnologia e escala', en: 'People, tech & scale' },
      areaName: { es: 'Sistemas ERP/inventario', pt: 'Sistemas ERP/inventário', en: 'ERP / inventory systems' },
      prompt: {
        es: '¿Qué sistemas existen y qué módulos se usan de verdad vs. subutilizados?',
        pt: 'Que sistemas existem e que módulos se usam de verdade vs. subutilizados?',
        en: 'What systems exist, and which modules are actually used vs underused?',
      },
      help: {
        es: 'Evidencia: stack, módulos activos',
        pt: 'Evidência: stack, módulos ativos',
        en: 'Evidence: stack, active modules',
      },
      level5: {
        es: 'Núcleo digital (stock, lotes, costos, ventas) actualizado el mismo día',
        pt: 'Núcleo digital (stock, lotes, custos, vendas) atualizado no mesmo dia',
        en: 'Digital core (stock, lots, costs, sales) same-day updated',
      },
      pillarSlug: 'digital',
      weight: 1.15,
    },
    {
      id: 'AIN-EXP-01',
      blockId: 'peo',
      blockLabel: { es: 'Personas, tecnología y escala', pt: 'Pessoas, tecnologia e escala', en: 'People, tech & scale' },
      areaName: { es: 'Certificaciones y replicabilidad', pt: 'Certificações e replicabilidade', en: 'Certifications & replicability' },
      prompt: {
        es: '¿Hay certificaciones activas o roadmap (BPM, HACCP, orgánico, BRC…)? ¿El modelo cabe en un manual de planta transferible?',
        pt: 'Há certificações ativas ou roadmap (BPM, HACCP, orgânico, BRC…)? O modelo cabe num manual de planta transferível?',
        en: 'Are there active certifications or a roadmap, and is the model a transferable plant manual?',
      },
      help: {
        es: 'Evidencia: certificados, gaps de auditoría',
        pt: 'Evidência: certificados, gaps de auditoria',
        en: 'Evidence: certificates, audit gaps',
      },
      level5: {
        es: 'Certificación objetivo con gap plan + manual de planta',
        pt: 'Certificação alvo com gap plan + manual de planta',
        en: 'Target certification with gap plan + plant manual',
      },
      pillarSlug: 'strategy',
      weight: 1.2,
    },
  ],
};
