import type { FieldEntryKind, SectorModule } from './types';

const AGRO_ENTRIES: FieldEntryKind[] = [
  'planting',
  'input',
  'irrigation',
  'pest',
  'harvest',
  'observation',
  'visit',
];

export const AGRICULTURE_MODULE: SectorModule = {
  moduleId: 'agriculture',
  sectorIds: ['agriculture', 'horticulture'],
  unitKind: 'parcel',
  unitLabel: { es: 'Parcela', pt: 'Parcela', en: 'Parcel' },
  bookLabel: { es: 'Cuaderno de campo', pt: 'Caderno de campo', en: 'Field book' },
  monitorLabel: { es: 'Monitoreo de finca', pt: 'Monitorização da exploração', en: 'Farm monitoring' },
  intro: {
    es: 'La finca: parcelas, cuaderno y sensores en el mismo módulo.',
    pt: 'A exploração: parcelas, caderno e sensores no mesmo módulo.',
    en: 'The farm: parcels, field book and sensors in one module.',
  },
  namePlaceholder: { es: 'Parcela norte', pt: 'Parcela norte', en: 'North parcel' },
  showAreaHa: true,
  cropLabel: { es: 'Cultivo', pt: 'Cultura', en: 'Crop' },
  entryKinds: AGRO_ENTRIES,
  metrics: [
    { id: 'soil_moisture', label: { es: 'Humedad del suelo', pt: 'Humidade do solo', en: 'Soil moisture' }, unit: '%' },
    { id: 'irrigation_mm', label: { es: 'Riego (mm)', pt: 'Irrigação (mm)', en: 'Irrigation (mm)' }, unit: 'mm' },
    { id: 'temperature', label: { es: 'Temperatura', pt: 'Temperatura', en: 'Temperature' }, unit: '°C' },
    { id: 'input_applied', label: { es: 'Insumo aplicado', pt: 'Insumo aplicado', en: 'Input applied' }, unit: 'kg/ha' },
  ],
  protocols: [
    {
      id: 'planting_cycle',
      title: { es: 'Ciclo / siembra por parcela', pt: 'Ciclo / sementeira por parcela', en: 'Planting cycle per parcel' },
      summary: {
        es: 'Registrar cultivo, fecha de siembra y densidad en cada parcela.',
        pt: 'Registar cultura, data de sementeira e densidade em cada parcela.',
        en: 'Record crop, planting date and density on each parcel.',
      },
      entryKinds: ['planting'],
      rules: [{ type: 'stale_book', days: 21 }],
      dxQuestionIds: ['sec_agr_plan', 'sec_hor_calendar'],
    },
    {
      id: 'input_phi',
      title: { es: 'Insumos y carencia (PHI)', pt: 'Insumos e carência (PHI)', en: 'Inputs and PHI' },
      summary: {
        es: 'Toda aplicación queda en el cuaderno. Cosecha bloqueada durante la carencia.',
        pt: 'Toda aplicação fica no caderno. Colheita bloqueada durante a carência.',
        en: 'Every application is logged. Harvest is blocked during the PHI window.',
      },
      entryKinds: ['input'],
      rules: [{ type: 'phi', days: 7 }],
      dxQuestionIds: ['sec_agr_inputs'],
    },
    {
      id: 'irrigation',
      title: { es: 'Riego (manual + umbral de sensor)', pt: 'Irrigação (manual + limiar de sensor)', en: 'Irrigation (manual + sensor threshold)' },
      summary: {
        es: 'Regar por criterio, no por turno fijo. Alerta si humedad < 25%.',
        pt: 'Regar por critério, não por turno fixo. Alerta se humidade < 25%.',
        en: 'Irrigate by criterion, not fixed turns. Alert if moisture < 25%.',
      },
      entryKinds: ['irrigation'],
      rules: [{ type: 'moisture_threshold', metric: 'soil_moisture', below: 25 }],
      dxQuestionIds: ['sec_agr_water', 'sec_hor_post'],
    },
    {
      id: 'mip_scout',
      title: { es: 'MIP / observación de plaga', pt: 'MIP / observação de praga', en: 'IPM / pest scouting' },
      summary: {
        es: 'Recorrido de observación con umbral antes de aplicar.',
        pt: 'Percurso de observação com limiar antes de aplicar.',
        en: 'Scouting walk with a threshold before spraying.',
      },
      entryKinds: ['pest', 'observation'],
      rules: [{ type: 'stale_book', days: 14 }],
      dxQuestionIds: ['sec_agr_book', 'sec_hor_book'],
    },
    {
      id: 'harvest_lot',
      title: { es: 'Cosecha y lote', pt: 'Colheita e lote', en: 'Harvest and lot' },
      summary: {
        es: 'Cosecha con código de lote. Respetar carencia del último insumo.',
        pt: 'Colheita com código de lote. Respeitar carência do último insumo.',
        en: 'Harvest with a lot code. Honour the last input PHI.',
      },
      entryKinds: ['harvest'],
      rules: [{ type: 'phi', days: 7 }],
      dxQuestionIds: ['sec_agr_market', 'sec_hor_sales'],
    },
  ],
  planSeeds: [
    {
      id: 'agro_register_parcels',
      title: {
        es: 'Registrar parcelas de la finca',
        pt: 'Registar parcelas da exploração',
        en: 'Register farm parcels',
      },
      description: {
        es: 'Abrir el módulo agrícola y crear cada parcela (nombre, ha, cultivo).',
        pt: 'Abrir o módulo agrícola e criar cada parcela (nome, ha, cultura).',
        en: 'Open the farm module and create each parcel (name, ha, crop).',
      },
      pillar: 'operations',
      priority: 'critical',
      kind: 'ops_unit',
      estimatedHours: 3,
      href: 'campo',
      protocolId: 'planting_cycle',
      dxQuestionIds: ['sec_agr_plan', 'sec_hor_calendar'],
    },
    {
      id: 'agro_open_field_book',
      title: {
        es: 'Abrir el cuaderno de campo de esta semana',
        pt: 'Abrir o caderno de campo desta semana',
        en: 'Open this week’s field book',
      },
      description: {
        es: 'Primera línea real: siembra, riego o insumo — no un recordatorio genérico.',
        pt: 'Primeira linha real: sementeira, irrigação ou insumo — não um lembrete genérico.',
        en: 'A real first line: planting, irrigation or input — not a generic reminder.',
      },
      pillar: 'sector',
      priority: 'critical',
      kind: 'field_book',
      estimatedHours: 2,
      href: 'campo',
      protocolId: 'mip_scout',
      dxQuestionIds: ['sec_agr_book', 'sec_hor_book'],
    },
    {
      id: 'agro_moisture_sensor',
      title: {
        es: 'Ligar sensor de humedad en una parcela',
        pt: 'Ligar sensor de humidade numa parcela',
        en: 'Connect a moisture sensor on one parcel',
      },
      description: {
        es: 'Registrar el sensor en Monitorización y enviar la primera lectura HTTP.',
        pt: 'Registar o sensor em Monitorização e enviar a primeira leitura HTTP.',
        en: 'Register the sensor in Monitoring and send the first HTTP reading.',
      },
      pillar: 'digital',
      priority: 'high',
      kind: 'sensor',
      estimatedHours: 3,
      href: 'monitor',
      protocolId: 'irrigation',
      dxQuestionIds: ['sec_agr_water', 'sec_hor_post'],
    },
    {
      id: 'agro_phi_protocol',
      title: {
        es: 'Aplicar protocolo de carencia (PHI) en insumos',
        pt: 'Aplicar protocolo de carência (PHI) em insumos',
        en: 'Apply the PHI protocol on inputs',
      },
      description: {
        es: 'Toda aplicación con producto, dosis y días de carencia en el cuaderno.',
        pt: 'Toda aplicação com produto, dose e dias de carência no caderno.',
        en: 'Every spray with product, dose and PHI days in the field book.',
      },
      pillar: 'risk',
      priority: 'high',
      kind: 'protocol',
      estimatedHours: 4,
      href: 'campo',
      protocolId: 'input_phi',
      dxQuestionIds: ['sec_agr_inputs'],
    },
    {
      id: 'agro_harvest_lot',
      title: {
        es: 'Cerrar cosecha con lote y canal',
        pt: 'Fechar colheita com lote e canal',
        en: 'Close harvest with lot and channel',
      },
      description: {
        es: 'Cada despacho con código de lote en el cuaderno — no vender a ciegas.',
        pt: 'Cada expedição com código de lote no caderno — não vender às cegas.',
        en: 'Every dispatch with a lot code in the book — do not sell blind.',
      },
      pillar: 'commercial',
      priority: 'high',
      kind: 'protocol',
      estimatedHours: 3,
      href: 'campo',
      protocolId: 'harvest_lot',
      dxQuestionIds: ['sec_agr_market', 'sec_hor_sales'],
    },
  ],
};
