import type { FieldEntryKind, SectorModule } from './types';

const ENTRIES: FieldEntryKind[] = ['hygiene', 'process', 'qc', 'input', 'harvest', 'observation', 'visit'];

export const AGROINDUSTRY_MODULE: SectorModule = {
  moduleId: 'agroindustry',
  sectorIds: ['agroindustry'],
  unitKind: 'lot',
  unitLabel: { es: 'Línea / lote', pt: 'Linha / lote', en: 'Line / lot' },
  bookLabel: { es: 'Cuaderno de planta', pt: 'Caderno de planta', en: 'Plant book' },
  monitorLabel: { es: 'Monitoreo de planta', pt: 'Monitorização da planta', en: 'Plant monitoring' },
  intro: {
    es: 'La planta: higiene diaria, lote, calidad y cadena de frío.',
    pt: 'A planta: higiene diária, lote, qualidade e cadeia de frio.',
    en: 'The plant: daily hygiene, lot, quality and cold chain.',
  },
  namePlaceholder: { es: 'Línea de mermelada', pt: 'Linha de doce', en: 'Jam line' },
  qtyLabel: { es: 'Capacidad (t)', pt: 'Capacidade (t)', en: 'Capacity (t)' },
  cropLabel: { es: 'Producto', pt: 'Produto', en: 'Product' },
  entryKinds: ENTRIES,
  metrics: [
    { id: 'temperature', label: { es: 'Temperatura de cámara', pt: 'Temperatura da câmara', en: 'Cold-room temperature' }, unit: '°C' },
    { id: 'waste_pct', label: { es: 'Merma', pt: 'Perda', en: 'Waste' }, unit: '%' },
  ],
  protocols: [
    {
      id: 'daily_hygiene',
      title: { es: 'Higiene diaria', pt: 'Higiene diária', en: 'Daily hygiene' },
      summary: {
        es: 'Checklist de zonas limpias/sucias — no un protocolo que existe y no se usa.',
        pt: 'Checklist de zonas limpas/sujas — não um protocolo que existe e não se usa.',
        en: 'Clean/dirty zone checklist — not a protocol that exists unused.',
      },
      entryKinds: ['hygiene'],
      rules: [{ type: 'stale_book', days: 1 }],
      dxQuestionIds: ['sec_agi_safety', 'sec_agi_book'],
    },
    {
      id: 'lot_trace',
      title: { es: 'Trazabilidad de lote', pt: 'Rastreabilidade de lote', en: 'Lot traceability' },
      summary: {
        es: 'Cada corrida con código de lote, insumos y destino.',
        pt: 'Cada corrida com código de lote, insumos e destino.',
        en: 'Each run with lot code, inputs and destination.',
      },
      entryKinds: ['process', 'harvest'],
      rules: [{ type: 'stale_book', days: 7 }],
      dxQuestionIds: ['sec_agi_process'],
    },
    {
      id: 'qc_release',
      title: { es: 'Liberación de calidad', pt: 'Liberação de qualidade', en: 'Quality release' },
      summary: {
        es: 'QC antes de despachar. Registrar no conformidad.',
        pt: 'QC antes de expedir. Registar não conformidade.',
        en: 'QC before dispatch. Log non-conformity.',
      },
      entryKinds: ['qc'],
      rules: [{ type: 'stale_book', days: 7 }],
      dxQuestionIds: ['sec_agi_b2b', 'sec_agi_safety'],
    },
    {
      id: 'cold_chain',
      title: { es: 'Cadena de frío', pt: 'Cadeia de frio', en: 'Cold chain' },
      summary: {
        es: 'Cámara por encima de 8 °C es alerta.',
        pt: 'Câmara acima de 8 °C é alerta.',
        en: 'Cold room above 8 °C is an alert.',
      },
      entryKinds: ['observation'],
      rules: [{ type: 'metric_threshold', metric: 'temperature', above: 8 }],
    },
    {
      id: 'waste_watch',
      title: { es: 'Merma de proceso', pt: 'Perda de processo', en: 'Process waste' },
      summary: {
        es: 'Alerta si la merma supera 12%.',
        pt: 'Alerta se a perda supera 12%.',
        en: 'Alert if waste exceeds 12%.',
      },
      entryKinds: ['process'],
      rules: [{ type: 'metric_threshold', metric: 'waste_pct', above: 12 }],
    },
  ],
  planSeeds: [
    {
      id: 'ind_register_line',
      title: {
        es: 'Registrar líneas y productos de planta',
        pt: 'Registar linhas e produtos da planta',
        en: 'Register plant lines and products',
      },
      description: {
        es: 'Cada línea: producto, capacidad y turno.',
        pt: 'Cada linha: produto, capacidade e turno.',
        en: 'Each line: product, capacity and shift.',
      },
      pillar: 'operations',
      priority: 'critical',
      kind: 'ops_unit',
      estimatedHours: 3,
      href: 'campo',
    },
    {
      id: 'ind_open_book',
      title: {
        es: 'Abrir el cuaderno de planta de hoy',
        pt: 'Abrir o caderno de planta de hoje',
        en: 'Open today’s plant book',
      },
      description: {
        es: 'Higiene o lote de la corrida — no un checklist teórico.',
        pt: 'Higiene ou lote da corrida — não um checklist teórico.',
        en: 'Hygiene or the run’s lot — not a theoretical checklist.',
      },
      pillar: 'sector',
      priority: 'critical',
      kind: 'field_book',
      estimatedHours: 2,
      href: 'campo',
      protocolId: 'daily_hygiene',
      dxQuestionIds: ['sec_agi_book'],
    },
    {
      id: 'ind_cold_sensor',
      title: {
        es: 'Ligar sensor de cámara fría',
        pt: 'Ligar sensor da câmara fria',
        en: 'Connect a cold-room sensor',
      },
      description: {
        es: 'Registrar el sensor y enviar la primera lectura HTTP.',
        pt: 'Registar o sensor e enviar a primeira leitura HTTP.',
        en: 'Register the sensor and send the first HTTP reading.',
      },
      pillar: 'digital',
      priority: 'high',
      kind: 'sensor',
      estimatedHours: 3,
      href: 'monitor',
      protocolId: 'cold_chain',
    },
    {
      id: 'ind_hygiene',
      title: {
        es: 'Protocolo de higiene diaria en uso',
        pt: 'Protocolo de higiene diária em uso',
        en: 'Daily hygiene protocol in use',
      },
      description: {
        es: 'Una línea real por turno, no un PDF en la pared.',
        pt: 'Uma linha real por turno, não um PDF na parede.',
        en: 'One real line per shift, not a PDF on the wall.',
      },
      pillar: 'risk',
      priority: 'high',
      kind: 'protocol',
      estimatedHours: 4,
      href: 'campo',
      protocolId: 'daily_hygiene',
      dxQuestionIds: ['sec_agi_safety'],
    },
    {
      id: 'ind_lot',
      title: {
        es: 'Trazar cada corrida con código de lote',
        pt: 'Rastrear cada corrida com código de lote',
        en: 'Trace each run with a lot code',
      },
      description: {
        es: 'Insumos, proceso y destino en el cuaderno de planta.',
        pt: 'Insumos, processo e destino no caderno de planta.',
        en: 'Inputs, process and destination in the plant book.',
      },
      pillar: 'operations',
      priority: 'high',
      kind: 'protocol',
      estimatedHours: 4,
      href: 'campo',
      protocolId: 'lot_trace',
      dxQuestionIds: ['sec_agi_process'],
    },
    {
      id: 'ind_qc',
      title: {
        es: 'Liberar calidad antes de despachar',
        pt: 'Liberar qualidade antes de expedir',
        en: 'Release quality before dispatch',
      },
      description: {
        es: 'QC y no conformidad en el cuaderno — evidencia para B2B.',
        pt: 'QC e não conformidade no caderno — evidência para B2B.',
        en: 'QC and non-conformity in the book — evidence for B2B.',
      },
      pillar: 'commercial',
      priority: 'high',
      kind: 'protocol',
      estimatedHours: 3,
      href: 'campo',
      protocolId: 'qc_release',
      dxQuestionIds: ['sec_agi_b2b'],
    },
  ],
};
