import type { FieldEntryKind, SectorModule } from './types';

const ENTRIES: FieldEntryKind[] = ['hive_inspect', 'pest', 'input', 'harvest', 'observation', 'visit'];

export const APICULTURE_MODULE: SectorModule = {
  moduleId: 'apiculture',
  sectorIds: ['apiculture'],
  unitKind: 'hive',
  unitLabel: { es: 'Colmena / apiario', pt: 'Colmeia / apiário', en: 'Hive / apiary' },
  bookLabel: { es: 'Cuaderno apícola', pt: 'Caderno apícola', en: 'Hive book' },
  monitorLabel: { es: 'Monitoreo de colmenas', pt: 'Monitorização de colmeias', en: 'Hive monitoring' },
  intro: {
    es: 'El apiario: inspección, varroa, flora y cosecha con carencia.',
    pt: 'O apiário: inspeção, varroa, flora e colheita com carência.',
    en: 'The apiary: inspection, varroa, forage and harvest with withdrawal.',
  },
  namePlaceholder: { es: 'Apiario monte · colmena 4', pt: 'Apiário monte · colmeia 4', en: 'Hill apiary · hive 4' },
  qtyLabel: { es: 'Colmenas', pt: 'Colmeias', en: 'Hives' },
  cropLabel: { es: 'Flora / ubicación', pt: 'Flora / localização', en: 'Forage / site' },
  entryKinds: ENTRIES,
  metrics: [
    { id: 'temperature', label: { es: 'Temperatura de colmena', pt: 'Temperatura da colmeia', en: 'Hive temperature' }, unit: '°C' },
    { id: 'varroa_count', label: { es: 'Varroa (conteo)', pt: 'Varroa (contagem)', en: 'Varroa (count)' }, unit: 'u' },
    { id: 'humidity', label: { es: 'Humedad', pt: 'Humidade', en: 'Humidity' }, unit: '%' },
  ],
  protocols: [
    {
      id: 'hive_inspect',
      title: { es: 'Inspección de colmena', pt: 'Inspeção de colmeia', en: 'Hive inspection' },
      summary: {
        es: 'Reina, cría, reservas y espacio — al menos cada 21 días en temporada.',
        pt: 'Rainha, cria, reservas e espaço — pelo menos a cada 21 dias em temporada.',
        en: 'Queen, brood, stores and space — at least every 21 days in season.',
      },
      entryKinds: ['hive_inspect'],
      rules: [{ type: 'stale_book', days: 21 }],
      dxQuestionIds: ['sec_api_book', 'sec_api_health'],
    },
    {
      id: 'varroa',
      title: { es: 'Varroa / nosema', pt: 'Varroa / nosema', en: 'Varroa / nosema' },
      summary: {
        es: 'Conteo y umbral antes de tratar. Alerta si varroa > 3.',
        pt: 'Contagem e limiar antes de tratar. Alerta se varroa > 3.',
        en: 'Count and threshold before treating. Alert if varroa > 3.',
      },
      entryKinds: ['pest', 'hive_inspect'],
      rules: [
        { type: 'stale_book', days: 21 },
        { type: 'metric_threshold', metric: 'varroa_count', above: 3 },
      ],
      dxQuestionIds: ['sec_api_health'],
    },
    {
      id: 'treatment_phi',
      title: { es: 'Tratamiento y carencia de miel', pt: 'Tratamento e carência do mel', en: 'Treatment and honey PHI' },
      summary: {
        es: 'Producto aplicado y días antes de cosechar.',
        pt: 'Produto aplicado e dias antes de colher.',
        en: 'Product applied and days before harvest.',
      },
      entryKinds: ['input'],
      rules: [{ type: 'withdrawal', days: 30 }],
    },
    {
      id: 'flora_siting',
      title: { es: 'Flora y ubicación', pt: 'Flora e localização', en: 'Forage and siting' },
      summary: {
        es: 'Floración, trashumancia y vecinos — no dejar el apiario sin nota un mes.',
        pt: 'Floração, transumância e vizinhos — não deixar o apiário sem nota um mês.',
        en: 'Bloom, migration and neighbours — do not leave the apiary a month without a note.',
      },
      entryKinds: ['observation'],
      rules: [{ type: 'stale_book', days: 30 }],
      dxQuestionIds: ['sec_api_forage'],
    },
    {
      id: 'honey_harvest',
      title: { es: 'Cosecha y extracción', pt: 'Colheita e extração', en: 'Harvest and extraction' },
      summary: {
        es: 'Lote de miel con origen de colmenas. Respetar carencia.',
        pt: 'Lote de mel com origem das colmeias. Respeitar carência.',
        en: 'Honey lot with hive origin. Honour withdrawal.',
      },
      entryKinds: ['harvest'],
      rules: [{ type: 'withdrawal', days: 30 }],
      dxQuestionIds: ['sec_api_harvest', 'sec_api_sales'],
    },
  ],
  planSeeds: [
    {
      id: 'api_register_hives',
      title: {
        es: 'Registrar apiarios y colmenas',
        pt: 'Registar apiários e colmeias',
        en: 'Register apiaries and hives',
      },
      description: {
        es: 'Cada apiario: número de colmenas, flora y ubicación.',
        pt: 'Cada apiário: número de colmeias, flora e localização.',
        en: 'Each apiary: hive count, forage and site.',
      },
      pillar: 'operations',
      priority: 'critical',
      kind: 'ops_unit',
      estimatedHours: 3,
      href: 'campo',
    },
    {
      id: 'api_open_book',
      title: {
        es: 'Abrir el cuaderno apícola de esta quincena',
        pt: 'Abrir o caderno apícola desta quinzena',
        en: 'Open this fortnight’s hive book',
      },
      description: {
        es: 'Inspección o conteo de varroa — no un recordatorio.',
        pt: 'Inspeção ou contagem de varroa — não um lembrete.',
        en: 'An inspection or varroa count — not a reminder.',
      },
      pillar: 'sector',
      priority: 'critical',
      kind: 'field_book',
      estimatedHours: 2,
      href: 'campo',
      protocolId: 'hive_inspect',
      dxQuestionIds: ['sec_api_book'],
    },
    {
      id: 'api_hive_sensor',
      title: {
        es: 'Ligar sensor de temperatura en una colmena',
        pt: 'Ligar sensor de temperatura numa colmeia',
        en: 'Connect a temperature sensor on one hive',
      },
      description: {
        es: 'Registrar el sensor y enviar la primera lectura HTTP.',
        pt: 'Registar o sensor e enviar a primeira leitura HTTP.',
        en: 'Register the sensor and send the first HTTP reading.',
      },
      pillar: 'digital',
      priority: 'high',
      kind: 'sensor',
      estimatedHours: 3,
      href: 'monitor',
    },
    {
      id: 'api_varroa',
      title: {
        es: 'Protocolo de varroa con umbral',
        pt: 'Protocolo de varroa com limiar',
        en: 'Varroa protocol with a threshold',
      },
      description: {
        es: 'Conteo antes de tratar; carencia antes de cosechar miel.',
        pt: 'Contagem antes de tratar; carência antes de colher mel.',
        en: 'Count before treating; withdrawal before honey harvest.',
      },
      pillar: 'risk',
      priority: 'high',
      kind: 'protocol',
      estimatedHours: 4,
      href: 'campo',
      protocolId: 'varroa',
      dxQuestionIds: ['sec_api_health'],
    },
    {
      id: 'api_flora',
      title: {
        es: 'Anotar flora y ubicación del apiario',
        pt: 'Anotar flora e localização do apiário',
        en: 'Log forage and apiary siting',
      },
      description: {
        es: 'Floración, trashumancia y vecinos en el cuaderno — no solo memoria.',
        pt: 'Floração, transumância e vizinhos no caderno — não só memória.',
        en: 'Bloom, migration and neighbours in the book — not memory alone.',
      },
      pillar: 'operations',
      priority: 'high',
      kind: 'protocol',
      estimatedHours: 3,
      href: 'campo',
      protocolId: 'flora_siting',
      dxQuestionIds: ['sec_api_forage'],
    },
    {
      id: 'api_harvest_lot',
      title: {
        es: 'Cosecha de miel con lote y carencia',
        pt: 'Colheita de mel com lote e carência',
        en: 'Honey harvest with lot and withdrawal',
      },
      description: {
        es: 'Cada extracción con origen de colmenas y días de retiro.',
        pt: 'Cada extração com origem das colmeias e dias de retirada.',
        en: 'Each extraction with hive origin and withdrawal days.',
      },
      pillar: 'commercial',
      priority: 'high',
      kind: 'protocol',
      estimatedHours: 3,
      href: 'campo',
      protocolId: 'honey_harvest',
      dxQuestionIds: ['sec_api_harvest', 'sec_api_sales'],
    },
  ],
};
