import type { FieldEntryKind, SectorModule } from './types';

const ENTRIES: FieldEntryKind[] = ['health', 'feed', 'milking', 'input', 'harvest', 'observation', 'visit'];

export const LIVESTOCK_MODULE: SectorModule = {
  moduleId: 'livestock',
  sectorIds: ['livestock'],
  unitKind: 'herd',
  unitLabel: { es: 'Rebaño / lote', pt: 'Rebanho / lote', en: 'Herd / lot' },
  bookLabel: { es: 'Cuaderno zootécnico', pt: 'Caderno zootécnico', en: 'Herd book' },
  monitorLabel: { es: 'Monitoreo del rebaño', pt: 'Monitorização do rebanho', en: 'Herd monitoring' },
  intro: {
    es: 'El rebaño: sanidad, alimentación, leche y carencia de tratamientos.',
    pt: 'O rebanho: sanidade, alimentação, leite e carência de tratamentos.',
    en: 'The herd: health, feed, milk and treatment withdrawal.',
  },
  namePlaceholder: { es: 'Lote de vacas 1', pt: 'Lote de vacas 1', en: 'Cow lot 1' },
  qtyLabel: { es: 'Cabezas', pt: 'Cabeças', en: 'Head' },
  cropLabel: { es: 'Especie / raza', pt: 'Espécie / raça', en: 'Species / breed' },
  entryKinds: ENTRIES,
  metrics: [
    { id: 'temperature', label: { es: 'Temperatura (animal / tanque)', pt: 'Temperatura (animal / tanque)', en: 'Temperature (animal / tank)' }, unit: '°C' },
    { id: 'milk_l', label: { es: 'Leche (L)', pt: 'Leite (L)', en: 'Milk (L)' }, unit: 'L' },
    { id: 'mortality_pct', label: { es: 'Mortalidad', pt: 'Mortalidade', en: 'Mortality' }, unit: '%' },
  ],
  protocols: [
    {
      id: 'herd_register',
      title: { es: 'Censo del rebaño', pt: 'Censo do rebanho', en: 'Herd census' },
      summary: {
        es: 'Cada lote con especie, cabezas y responsable.',
        pt: 'Cada lote com espécie, cabeças e responsável.',
        en: 'Each lot with species, headcount and owner.',
      },
      entryKinds: ['observation'],
      rules: [{ type: 'stale_book', days: 14 }],
      dxQuestionIds: ['sec_liv_book'],
    },
    {
      id: 'health_calendar',
      title: { es: 'Calendario sanitario', pt: 'Calendário sanitário', en: 'Health calendar' },
      summary: {
        es: 'Vacunas, desparasitación y eventos clínicos en el cuaderno.',
        pt: 'Vacinas, desparasitação e eventos clínicos no caderno.',
        en: 'Vaccines, deworming and clinical events in the book.',
      },
      entryKinds: ['health'],
      rules: [{ type: 'stale_book', days: 7 }],
      dxQuestionIds: ['sec_liv_health'],
    },
    {
      id: 'treatment_withdrawal',
      title: { es: 'Carencia de tratamientos', pt: 'Carência de tratamentos', en: 'Treatment withdrawal' },
      summary: {
        es: 'Antibiótico o antiparasitario con días de retiro antes de leche/carne.',
        pt: 'Antibiótico ou antiparasitário com dias de retirada antes de leite/carne.',
        en: 'Antibiotic or antiparasitic with withdrawal days before milk/meat.',
      },
      entryKinds: ['health', 'input'],
      rules: [{ type: 'withdrawal', days: 7 }],
      dxQuestionIds: ['sec_liv_health'],
    },
    {
      id: 'feed_log',
      title: { es: 'Alimentación diaria', pt: 'Alimentação diária', en: 'Daily feed' },
      summary: {
        es: 'Ración y origen del alimento — no solo memoria.',
        pt: 'Ração e origem do alimento — não só memória.',
        en: 'Ration and feed origin — not memory alone.',
      },
      entryKinds: ['feed'],
      rules: [{ type: 'stale_book', days: 3 }],
    },
    {
      id: 'milk_cold',
      title: { es: 'Cadena de frío de la leche', pt: 'Cadeia de frio do leite', en: 'Milk cold chain' },
      summary: {
        es: 'Tanque por encima de 6 °C es alerta.',
        pt: 'Tanque acima de 6 °C é alerta.',
        en: 'Tank above 6 °C is an alert.',
      },
      entryKinds: ['milking'],
      rules: [{ type: 'metric_threshold', metric: 'temperature', above: 6 }],
      dxQuestionIds: ['sec_liv_cold'],
    },
  ],
  planSeeds: [
    {
      id: 'liv_register_herd',
      title: {
        es: 'Registrar rebaños / lotes',
        pt: 'Registar rebanhos / lotes',
        en: 'Register herds / lots',
      },
      description: {
        es: 'Abrir el módulo pecuario y crear cada lote (especie, cabezas).',
        pt: 'Abrir o módulo pecuário e criar cada lote (espécie, cabeças).',
        en: 'Open the livestock module and create each lot (species, head).',
      },
      pillar: 'operations',
      priority: 'critical',
      kind: 'ops_unit',
      estimatedHours: 3,
      href: 'campo',
      protocolId: 'herd_register',
      dxQuestionIds: ['sec_liv_book'],
    },
    {
      id: 'liv_open_book',
      title: {
        es: 'Abrir el cuaderno zootécnico de esta semana',
        pt: 'Abrir o caderno zootécnico desta semana',
        en: 'Open this week’s herd book',
      },
      description: {
        es: 'Primera línea: sanidad, ración o ordeño real.',
        pt: 'Primeira linha: sanidade, ração ou ordenha real.',
        en: 'First line: a real health, feed or milking record.',
      },
      pillar: 'sector',
      priority: 'critical',
      kind: 'field_book',
      estimatedHours: 2,
      href: 'campo',
      protocolId: 'health_calendar',
      dxQuestionIds: ['sec_liv_book'],
    },
    {
      id: 'liv_temp_sensor',
      title: {
        es: 'Ligar sensor de temperatura del tanque / corral',
        pt: 'Ligar sensor de temperatura do tanque / curral',
        en: 'Connect a tank / pen temperature sensor',
      },
      description: {
        es: 'Registrar el sensor y enviar la primera lectura HTTP.',
        pt: 'Registar o sensor e enviar a primeira leitura HTTP.',
        en: 'Register the sensor and send the first HTTP reading.',
      },
      pillar: 'digital',
      priority: 'high',
      kind: 'sensor',
      estimatedHours: 3,
      href: 'monitor',
      protocolId: 'milk_cold',
      dxQuestionIds: ['sec_liv_cold'],
    },
    {
      id: 'liv_withdrawal',
      title: {
        es: 'Aplicar carencia en todo tratamiento',
        pt: 'Aplicar carência em todo tratamento',
        en: 'Apply withdrawal on every treatment',
      },
      description: {
        es: 'Producto, lote tratado y días de retiro en el cuaderno.',
        pt: 'Produto, lote tratado e dias de retirada no caderno.',
        en: 'Product, treated lot and withdrawal days in the book.',
      },
      pillar: 'risk',
      priority: 'high',
      kind: 'protocol',
      estimatedHours: 4,
      href: 'campo',
      protocolId: 'treatment_withdrawal',
      dxQuestionIds: ['sec_liv_health'],
    },
  ],
};
