import type { FieldEntryKind, SectorModule } from './types';

const ENTRIES: FieldEntryKind[] = ['biosecurity', 'health', 'feed', 'egg', 'observation', 'visit'];

export const POULTRY_MODULE: SectorModule = {
  moduleId: 'poultry',
  sectorIds: ['poultry'],
  unitKind: 'flock',
  unitLabel: { es: 'Galpón / lote de aves', pt: 'Galpão / lote de aves', en: 'House / flock' },
  bookLabel: { es: 'Cuaderno avícola', pt: 'Caderno avícola', en: 'Poultry book' },
  monitorLabel: { es: 'Monitoreo avícola', pt: 'Monitorização avícola', en: 'Poultry monitoring' },
  intro: {
    es: 'El galpón: bioseguridad, postura, ración y mortalidad.',
    pt: 'O galpão: biossegurança, postura, ração e mortalidade.',
    en: 'The house: biosecurity, laying, feed and mortality.',
  },
  namePlaceholder: { es: 'Galpón 2 · postura', pt: 'Galpão 2 · postura', en: 'House 2 · layers' },
  qtyLabel: { es: 'Aves', pt: 'Aves', en: 'Birds' },
  cropLabel: { es: 'Línea / raza', pt: 'Linha / raça', en: 'Line / breed' },
  entryKinds: ENTRIES,
  metrics: [
    { id: 'temperature', label: { es: 'Temperatura del galpón', pt: 'Temperatura do galpão', en: 'House temperature' }, unit: '°C' },
    { id: 'egg_count', label: { es: 'Huevos / día', pt: 'Ovos / dia', en: 'Eggs / day' }, unit: 'u' },
    { id: 'mortality_pct', label: { es: 'Mortalidad', pt: 'Mortalidade', en: 'Mortality' }, unit: '%' },
  ],
  protocols: [
    {
      id: 'biosecurity',
      title: { es: 'Bioseguridad a la entrada', pt: 'Biossegurança à entrada', en: 'Entry biosecurity' },
      summary: {
        es: 'Pediluvio, ropa y registro de visitas al galpón.',
        pt: 'Pedilúvio, roupa e registo de visitas ao galpão.',
        en: 'Footbath, clothing and visitor log to the house.',
      },
      entryKinds: ['biosecurity', 'visit'],
      rules: [{ type: 'stale_book', days: 3 }],
      dxQuestionIds: ['sec_pou_bio'],
    },
    {
      id: 'laying_log',
      title: { es: 'Postura diaria', pt: 'Postura diária', en: 'Daily laying' },
      summary: {
        es: 'Huevos recolectados y merma — no solo al final de la semana.',
        pt: 'Ovos recolhidos e merma — não só no fim da semana.',
        en: 'Eggs collected and loss — not only at week end.',
      },
      entryKinds: ['egg'],
      rules: [{ type: 'stale_book', days: 2 }],
      dxQuestionIds: ['sec_pou_book', 'sec_pou_sales'],
    },
    {
      id: 'mortality_watch',
      title: { es: 'Umbral de mortalidad', pt: 'Limiar de mortalidade', en: 'Mortality threshold' },
      summary: {
        es: 'Más de 2% en el lote exige visita y aislamiento.',
        pt: 'Mais de 2% no lote exige visita e isolamento.',
        en: 'Over 2% in the flock requires a visit and isolation.',
      },
      entryKinds: ['health'],
      rules: [{ type: 'metric_threshold', metric: 'mortality_pct', above: 2 }],
    },
    {
      id: 'house_temp',
      title: { es: 'Temperatura del galpón', pt: 'Temperatura do galpão', en: 'House temperature' },
      summary: {
        es: 'Alerta si el galpón pasa de 32 °C.',
        pt: 'Alerta se o galpão passa de 32 °C.',
        en: 'Alert if the house exceeds 32 °C.',
      },
      entryKinds: ['observation'],
      rules: [{ type: 'metric_threshold', metric: 'temperature', above: 32 }],
    },
    {
      id: 'feed_conversion',
      title: { es: 'Ración y conversión', pt: 'Ração e conversão', en: 'Ration and conversion' },
      summary: {
        es: 'Kg de alimento vs. huevo o peso — al menos cada 2 días.',
        pt: 'Kg de alimento vs. ovo ou peso — pelo menos a cada 2 dias.',
        en: 'Kg of feed vs. egg or weight — at least every 2 days.',
      },
      entryKinds: ['feed'],
      rules: [{ type: 'stale_book', days: 2 }],
      dxQuestionIds: ['sec_pou_cost'],
    },
  ],
  planSeeds: [
    {
      id: 'pou_register_house',
      title: {
        es: 'Registrar galpones y lotes de aves',
        pt: 'Registar galpões e lotes de aves',
        en: 'Register houses and flocks',
      },
      description: {
        es: 'Cada galpón: línea, número de aves y fecha de ingreso.',
        pt: 'Cada galpão: linha, número de aves e data de entrada.',
        en: 'Each house: line, bird count and intake date.',
      },
      pillar: 'operations',
      priority: 'critical',
      kind: 'ops_unit',
      estimatedHours: 3,
      href: 'campo',
    },
    {
      id: 'pou_open_book',
      title: {
        es: 'Abrir el cuaderno avícola de hoy',
        pt: 'Abrir o caderno avícola de hoje',
        en: 'Open today’s poultry book',
      },
      description: {
        es: 'Postura, mortalidad o ración — una línea real.',
        pt: 'Postura, mortalidade ou ração — uma linha real.',
        en: 'Laying, mortality or feed — one real line.',
      },
      pillar: 'sector',
      priority: 'critical',
      kind: 'field_book',
      estimatedHours: 2,
      href: 'campo',
      protocolId: 'laying_log',
      dxQuestionIds: ['sec_pou_book'],
    },
    {
      id: 'pou_temp_sensor',
      title: {
        es: 'Ligar sensor de temperatura en un galpón',
        pt: 'Ligar sensor de temperatura num galpão',
        en: 'Connect a temperature sensor in one house',
      },
      description: {
        es: 'Registrar el sensor y mandar la primera lectura.',
        pt: 'Registar o sensor e enviar a primeira leitura.',
        en: 'Register the sensor and send the first reading.',
      },
      pillar: 'digital',
      priority: 'high',
      kind: 'sensor',
      estimatedHours: 3,
      href: 'monitor',
      protocolId: 'house_temp',
    },
    {
      id: 'pou_bio',
      title: {
        es: 'Protocolo de bioseguridad a la puerta',
        pt: 'Protocolo de biossegurança à porta',
        en: 'Door biosecurity protocol',
      },
      description: {
        es: 'Registrar cada visita al galpón y el pediluvio.',
        pt: 'Registar cada visita ao galpão e o pedilúvio.',
        en: 'Log every house visit and the footbath.',
      },
      pillar: 'risk',
      priority: 'high',
      kind: 'protocol',
      estimatedHours: 3,
      href: 'campo',
      protocolId: 'biosecurity',
      dxQuestionIds: ['sec_pou_bio'],
    },
    {
      id: 'pou_feed',
      title: {
        es: 'Registrar ración y conversión',
        pt: 'Registar ração e conversão',
        en: 'Log ration and conversion',
      },
      description: {
        es: 'Kg de alimento vs. huevo en el cuaderno — base del costo por unidad.',
        pt: 'Kg de alimento vs. ovo no caderno — base do custo por unidade.',
        en: 'Kg of feed vs. egg in the book — the unit-cost base.',
      },
      pillar: 'finance',
      priority: 'high',
      kind: 'protocol',
      estimatedHours: 3,
      href: 'campo',
      protocolId: 'feed_conversion',
      dxQuestionIds: ['sec_pou_cost'],
    },
    {
      id: 'pou_sales_lot',
      title: {
        es: 'Postura diaria como evidencia de venta',
        pt: 'Postura diária como evidência de venda',
        en: 'Daily laying as sales evidence',
      },
      description: {
        es: 'Huevos recolectados cada día — volumen real para el canal.',
        pt: 'Ovos recolhidos cada dia — volume real para o canal.',
        en: 'Eggs collected each day — real volume for the channel.',
      },
      pillar: 'commercial',
      priority: 'medium',
      kind: 'protocol',
      estimatedHours: 2,
      href: 'campo',
      protocolId: 'laying_log',
      dxQuestionIds: ['sec_pou_sales'],
    },
  ],
};
