// Predefined company budget lines and subcategories
export const DEFAULT_BUDGET_LINES = [
  {
    name: 'Personal / Personnel',
    nameEs: 'Personal / Personnel',
    namePt: 'Pessoal / Personnel',
    icon: 'Users',
    color: '#6366F1',
    order: 1,
    subcategories: [
      { name: 'HQ Based', nameEs: 'Basado en Sede', namePt: 'Baseado na Sede' },
      { name: 'Field Based', nameEs: 'Basado en Campo', namePt: 'Baseado em Campo' },
    ],
  },
  {
    name: 'Travel',
    nameEs: 'Viajes / Travel',
    namePt: 'Viagens / Travel',
    icon: 'Plane',
    color: '#3B82F6',
    order: 2,
    subcategories: [
      { name: 'Airfare', nameEs: 'Pasajes A\u00e9reos', namePt: 'Passagens A\u00e9reas' },
      { name: 'Lodging', nameEs: 'Alojamiento', namePt: 'Hospedagem' },
      { name: 'Per Diem / Meals', nameEs: 'Per Diem / Comidas', namePt: 'Di\u00e1rias / Refei\u00e7\u00f5es' },
      { name: 'Ground Transport', nameEs: 'Transporte Terrestre', namePt: 'Transporte Terrestre' },
      { name: 'Car Rental', nameEs: 'Alquiler de Auto', namePt: 'Aluguel de Ve\u00edculo' },
      { name: 'Fuel', nameEs: 'Combustible', namePt: 'Combust\u00edvel' },
      { name: 'Travel Insurance', nameEs: 'Seguro de Viaje', namePt: 'Seguro de Viagem' },
    ],
  },
  {
    name: 'Contractual / Services',
    nameEs: 'Contractual / Servicios',
    namePt: 'Contratual / Servi\u00e7os',
    icon: 'FileSignature',
    color: '#8B5CF6',
    order: 3,
    subcategories: [
      { name: 'Consulting', nameEs: 'Consultor\u00eda', namePt: 'Consultoria' },
      { name: 'Legal', nameEs: 'Legal', namePt: 'Jur\u00eddico' },
      { name: 'Accounting', nameEs: 'Contabilidad', namePt: 'Contabilidade' },
      { name: 'Audit', nameEs: 'Auditor\u00eda', namePt: 'Auditoria' },
    ],
  },
  {
    name: 'Software & Technology',
    nameEs: 'Software y Tecnolog\u00eda',
    namePt: 'Software e Tecnologia',
    icon: 'Laptop',
    color: '#06B6D4',
    order: 4,
    subcategories: [
      { name: 'Licenses', nameEs: 'Licencias', namePt: 'Licen\u00e7as' },
      { name: 'Hosting', nameEs: 'Hosting / Servidores', namePt: 'Hospedagem / Servidores' },
      { name: 'Development', nameEs: 'Desarrollo', namePt: 'Desenvolvimento' },
    ],
  },
  {
    name: 'Supplies & Equipment',
    nameEs: 'Suministros y Equipamiento',
    namePt: 'Suprimentos e Equipamentos',
    icon: 'Package',
    color: '#F59E0B',
    order: 5,
    subcategories: [
      { name: 'Office Supplies', nameEs: 'Suministros de Oficina', namePt: 'Material de Escrit\u00f3rio' },
      { name: 'Field Equipment', nameEs: 'Equipamiento de Campo', namePt: 'Equipamento de Campo' },
      { name: 'Furniture', nameEs: 'Mobiliario', namePt: 'Mobili\u00e1rio' },
    ],
  },
  {
    name: 'Communications',
    nameEs: 'Comunicaciones',
    namePt: 'Comunica\u00e7\u00f5es',
    icon: 'Wifi',
    color: '#10B981',
    order: 6,
    subcategories: [
      { name: 'Internet & Phone', nameEs: 'Internet y Tel\u00e9fono', namePt: 'Internet e Telefone' },
      { name: 'Marketing & Outreach', nameEs: 'Marketing y Difusi\u00f3n', namePt: 'Marketing e Divulga\u00e7\u00e3o' },
    ],
  },
  {
    name: 'Insurance & Taxes',
    nameEs: 'Seguros e Impuestos',
    namePt: 'Seguros e Impostos',
    icon: 'Shield',
    color: '#EF4444',
    order: 7,
    subcategories: [
      { name: 'Health Insurance', nameEs: 'Seguro de Salud', namePt: 'Seguro de Sa\u00fade' },
      { name: 'Liability', nameEs: 'Responsabilidad Civil', namePt: 'Responsabilidade Civil' },
      { name: 'Property Tax', nameEs: 'Impuesto Inmobiliario', namePt: 'IPTU / Imposto Predial' },
      { name: 'IRS Filings', nameEs: 'Declaraciones IRS', namePt: 'Declara\u00e7\u00f5es IRS' },
    ],
  },
  {
    name: 'Other',
    nameEs: 'Otros',
    namePt: 'Outros',
    icon: 'MoreHorizontal',
    color: '#6B7280',
    order: 8,
    subcategories: [
      { name: 'Miscellaneous', nameEs: 'Varios', namePt: 'Diversos' },
    ],
  },
];
