-- Forge feira / kiosk: sessão com código curto + inscrição por email

CREATE TABLE IF NOT EXISTS "ForgeFeriaSession" (
    "id" TEXT NOT NULL,
    "courseId" TEXT NOT NULL,
    "roomCode" TEXT NOT NULL,
    "title" TEXT,
    "teamSize" INTEGER NOT NULL DEFAULT 4,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ForgeFeriaSession_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "ForgeFeriaRegistration" (
    "id" TEXT NOT NULL,
    "sessionId" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "accessCode" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "ageRange" TEXT,
    "gender" TEXT,
    "locale" TEXT NOT NULL DEFAULT 'es',
    "playGroupId" TEXT NOT NULL,
    "registeredAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ForgeFeriaRegistration_pkey" PRIMARY KEY ("id")
);

ALTER TABLE "ForgePlayGroup" ADD COLUMN IF NOT EXISTS "feriaSessionId" TEXT;
ALTER TABLE "ForgePlayGroup" ADD COLUMN IF NOT EXISTS "autoGenerated" BOOLEAN NOT NULL DEFAULT false;

CREATE UNIQUE INDEX IF NOT EXISTS "ForgeFeriaSession_courseId_roomCode_key" ON "ForgeFeriaSession"("courseId", "roomCode");
CREATE INDEX IF NOT EXISTS "ForgeFeriaSession_roomCode_idx" ON "ForgeFeriaSession"("roomCode");
CREATE INDEX IF NOT EXISTS "ForgeFeriaSession_courseId_active_idx" ON "ForgeFeriaSession"("courseId", "active");

CREATE UNIQUE INDEX IF NOT EXISTS "ForgeFeriaRegistration_sessionId_email_key" ON "ForgeFeriaRegistration"("sessionId", "email");
CREATE UNIQUE INDEX IF NOT EXISTS "ForgeFeriaRegistration_sessionId_accessCode_key" ON "ForgeFeriaRegistration"("sessionId", "accessCode");
CREATE INDEX IF NOT EXISTS "ForgeFeriaRegistration_playGroupId_idx" ON "ForgeFeriaRegistration"("playGroupId");
CREATE INDEX IF NOT EXISTS "ForgeFeriaRegistration_userId_idx" ON "ForgeFeriaRegistration"("userId");
CREATE INDEX IF NOT EXISTS "ForgePlayGroup_feriaSessionId_idx" ON "ForgePlayGroup"("feriaSessionId");

ALTER TABLE "ForgeFeriaSession" DROP CONSTRAINT IF EXISTS "ForgeFeriaSession_courseId_fkey";
ALTER TABLE "ForgeFeriaSession" ADD CONSTRAINT "ForgeFeriaSession_courseId_fkey" FOREIGN KEY ("courseId") REFERENCES "ForgeCourse"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "ForgeFeriaRegistration" DROP CONSTRAINT IF EXISTS "ForgeFeriaRegistration_sessionId_fkey";
ALTER TABLE "ForgeFeriaRegistration" ADD CONSTRAINT "ForgeFeriaRegistration_sessionId_fkey" FOREIGN KEY ("sessionId") REFERENCES "ForgeFeriaSession"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "ForgeFeriaRegistration" DROP CONSTRAINT IF EXISTS "ForgeFeriaRegistration_userId_fkey";
ALTER TABLE "ForgeFeriaRegistration" ADD CONSTRAINT "ForgeFeriaRegistration_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "ForgeFeriaRegistration" DROP CONSTRAINT IF EXISTS "ForgeFeriaRegistration_playGroupId_fkey";
ALTER TABLE "ForgeFeriaRegistration" ADD CONSTRAINT "ForgeFeriaRegistration_playGroupId_fkey" FOREIGN KEY ("playGroupId") REFERENCES "ForgePlayGroup"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "ForgePlayGroup" DROP CONSTRAINT IF EXISTS "ForgePlayGroup_feriaSessionId_fkey";
ALTER TABLE "ForgePlayGroup" ADD CONSTRAINT "ForgePlayGroup_feriaSessionId_fkey" FOREIGN KEY ("feriaSessionId") REFERENCES "ForgeFeriaSession"("id") ON DELETE SET NULL ON UPDATE CASCADE;
