import { randomBytes } from 'crypto';
import type { Locale } from '@/lib/i18n';
import { getForgeDb } from '@/lib/forge/db';
import { ensureLearnerJourney } from '@/lib/forge/learner-journey';
import { generateMagicLoginToken, magicLoginExpiresAt } from '@/lib/forge/invite-auth';
import {
  buildFeriaSalaRedirect,
  generateFeriaCode,
  normalizeEmail,
  normalizeRoomCode,
  pickRandomGroup,
  type FeriaAgeRange,
  type FeriaGender,
  FERIA_AGE_RANGES,
  FERIA_GENDERS,
} from '@/lib/forge/feria-kiosk-core';

export {
  buildFeriaSalaRedirect,
  generateFeriaCode,
  normalizeEmail,
  normalizeRoomCode,
  pickRandomGroup,
  FERIA_AGE_RANGES,
  FERIA_GENDERS,
  type FeriaAgeRange,
  type FeriaGender,
};

export function isValidLocale(raw: string | undefined): raw is Locale {
  return raw === 'es' || raw === 'pt' || raw === 'en';
}

async function generateUniqueAccessCode(sessionId: string): Promise<string> {
  const db = getForgeDb();
  for (let attempt = 0; attempt < 24; attempt++) {
    const accessCode = generateFeriaCode(6);
    const exists = await db.forgeFeriaRegistration.findFirst({
      where: { sessionId, accessCode },
      select: { id: true },
    });
    if (!exists) return accessCode;
  }
  throw new Error('forge.feria.codeGenFailed');
}

async function assignRandomPlayGroup(session: {
  id: string;
  courseId: string;
  editionId?: string | null;
  teamSize: number;
}): Promise<{ id: string; name: string; teamNumber: number }> {
  const db = getForgeDb();
  const groups = await db.forgePlayGroup.findMany({
    where: { feriaSessionId: session.id, mode: 'live_team' },
    orderBy: { createdAt: 'asc' },
    include: { _count: { select: { enrollments: true } } },
  });

  const mapped = groups.map((g, idx) => ({
    id: g.id,
    name: g.name,
    memberCount: g._count.enrollments,
    teamNumber: idx + 1,
  }));

  const picked = pickRandomGroup(mapped, session.teamSize);
  if (picked) {
    return { id: picked.id, name: picked.name, teamNumber: picked.teamNumber };
  }

  const teamNumber = groups.length + 1;
  const inviteToken = randomBytes(24).toString('base64url');
  const expires = new Date();
  expires.setDate(expires.getDate() + 30);

  const created = await db.forgePlayGroup.create({
    data: {
      courseId: session.courseId,
      editionId: session.editionId ?? null,
      name: `Equipo ${teamNumber}`,
      mode: 'live_team',
      feriaSessionId: session.id,
      autoGenerated: true,
      inviteToken,
      inviteExpiresAt: expires,
    },
  });

  return { id: created.id, name: created.name, teamNumber };
}

export type FeriaRegisterInput = {
  roomCode: string;
  email: string;
  name: string;
  ageRange?: string | null;
  gender?: string | null;
  locale?: string;
  consent?: boolean;
};

export type FeriaRegisterResult = {
  ok: true;
  courseId: string;
  playGroupId: string;
  playGroupName: string;
  teamNumber: number;
  accessCode: string;
  redirect: string;
  magicLoginToken: string;
  existing: boolean;
};

export async function registerFeriaParticipant(
  input: FeriaRegisterInput
): Promise<FeriaRegisterResult> {
  const roomCode = normalizeRoomCode(input.roomCode);
  const email = normalizeEmail(input.email);
  const name = input.name.trim();
  const locale = isValidLocale(input.locale) ? input.locale : 'es';

  if (!roomCode) throw new Error('forge.feria.roomRequired');
  if (!email || !email.includes('@')) throw new Error('forge.feria.emailRequired');
  if (!name) throw new Error('forge.feria.nameRequired');
  if (!input.consent) throw new Error('forge.feria.consentRequired');

  const db = getForgeDb();
  const session = await db.forgeFeriaSession.findFirst({
    where: { roomCode, active: true },
    include: { course: { select: { id: true, title: true } } },
  });
  if (!session) throw new Error('forge.feria.invalidRoom');

  const existingReg = await db.forgeFeriaRegistration.findUnique({
    where: { sessionId_email: { sessionId: session.id, email } },
    include: { playGroup: { select: { id: true, name: true } } },
  });

  let user = await db.user.findUnique({ where: { email } });
  if (!user) {
    user = await db.user.create({
      data: {
        email,
        name,
        role: 'COLLABORATOR',
        isActive: true,
        locale,
      },
    });
  } else if (name && user.name !== name) {
    user = await db.user.update({ where: { id: user.id }, data: { name, locale } });
  }

  const magic = generateMagicLoginToken();

  if (existingReg) {
    await db.forgeFeriaRegistration.update({
      where: { id: existingReg.id },
      data: {
        name,
        ageRange: input.ageRange ?? existingReg.ageRange,
        gender: input.gender ?? existingReg.gender,
        locale,
      },
    });

    const enrollment = await db.forgeEnrollment.findUnique({
      where: { courseId_userId: { courseId: session.courseId, userId: user.id } },
    });
    if (enrollment) {
      await db.forgeEnrollment.update({
        where: { id: enrollment.id },
        data: {
          playGroupId: existingReg.playGroupId,
          status: 'active',
          magicLoginToken: magic,
          magicLoginExpiresAt: magicLoginExpiresAt(),
        },
      });
    } else {
      await db.forgeEnrollment.create({
        data: {
          courseId: session.courseId,
          userId: user.id,
          status: 'active',
          accessScope: 'course_only',
          playGroupId: existingReg.playGroupId,
          magicLoginToken: magic,
          magicLoginExpiresAt: magicLoginExpiresAt(),
        },
      });
    }

    await ensureLearnerJourney(session.courseId, user.id);

    const groups = await db.forgePlayGroup.findMany({
      where: { feriaSessionId: session.id, mode: 'live_team' },
      orderBy: { createdAt: 'asc' },
      select: { id: true },
    });
    const teamNumber = Math.max(1, groups.findIndex((g) => g.id === existingReg.playGroupId) + 1);

    return {
      ok: true,
      courseId: session.courseId,
      playGroupId: existingReg.playGroupId,
      playGroupName: existingReg.playGroup.name,
      teamNumber,
      accessCode: existingReg.accessCode,
      redirect: buildFeriaSalaRedirect(session.courseId, existingReg.playGroupId),
      magicLoginToken: magic,
      existing: true,
    };
  }

  const playGroup = await assignRandomPlayGroup({
    id: session.id,
    courseId: session.courseId,
    editionId: session.editionId,
    teamSize: session.teamSize,
  });

  const accessCode = await generateUniqueAccessCode(session.id);

  await db.forgeFeriaRegistration.create({
    data: {
      sessionId: session.id,
      userId: user.id,
      email,
      accessCode,
      name,
      ageRange: input.ageRange ?? null,
      gender: input.gender ?? null,
      locale,
      playGroupId: playGroup.id,
    },
  });

  const enrollment = await db.forgeEnrollment.findUnique({
    where: { courseId_userId: { courseId: session.courseId, userId: user.id } },
  });

  if (enrollment) {
    await db.forgeEnrollment.update({
      where: { id: enrollment.id },
      data: {
        playGroupId: playGroup.id,
        status: 'active',
        magicLoginToken: magic,
        magicLoginExpiresAt: magicLoginExpiresAt(),
      },
    });
  } else {
    await db.forgeEnrollment.create({
      data: {
        courseId: session.courseId,
        userId: user.id,
        status: 'active',
        accessScope: 'course_only',
        playGroupId: playGroup.id,
        magicLoginToken: magic,
        magicLoginExpiresAt: magicLoginExpiresAt(),
      },
    });
  }

  await ensureLearnerJourney(session.courseId, user.id);

  return {
    ok: true,
    courseId: session.courseId,
    playGroupId: playGroup.id,
    playGroupName: playGroup.name,
    teamNumber: playGroup.teamNumber,
    accessCode,
    redirect: buildFeriaSalaRedirect(session.courseId, playGroup.id),
    magicLoginToken: magic,
    existing: false,
  };
}

export type FeriaRejoinInput = {
  roomCode: string;
  email: string;
  accessCode: string;
};

export async function rejoinFeriaParticipant(input: FeriaRejoinInput): Promise<FeriaRegisterResult> {
  const roomCode = normalizeRoomCode(input.roomCode);
  const email = normalizeEmail(input.email);
  const accessCode = input.accessCode.trim().toUpperCase();

  if (!roomCode) throw new Error('forge.feria.roomRequired');
  if (!email) throw new Error('forge.feria.emailRequired');
  if (!accessCode) throw new Error('forge.feria.accessCodeRequired');

  const db = getForgeDb();
  const session = await db.forgeFeriaSession.findFirst({
    where: { roomCode, active: true },
  });
  if (!session) throw new Error('forge.feria.invalidRoom');

  const reg = await db.forgeFeriaRegistration.findFirst({
    where: {
      sessionId: session.id,
      email,
      accessCode,
    },
    include: { playGroup: { select: { id: true, name: true } } },
  });
  if (!reg) throw new Error('forge.feria.invalidCredentials');

  const magic = generateMagicLoginToken();
  await db.forgeEnrollment.updateMany({
    where: { courseId: session.courseId, userId: reg.userId },
    data: {
      playGroupId: reg.playGroupId,
      status: 'active',
      magicLoginToken: magic,
      magicLoginExpiresAt: magicLoginExpiresAt(),
    },
  });

  await ensureLearnerJourney(session.courseId, reg.userId);

  const groups = await db.forgePlayGroup.findMany({
    where: { feriaSessionId: session.id, mode: 'live_team' },
    orderBy: { createdAt: 'asc' },
    select: { id: true },
  });
  const teamNumber = Math.max(1, groups.findIndex((g) => g.id === reg.playGroupId) + 1);

  return {
    ok: true,
    courseId: session.courseId,
    playGroupId: reg.playGroupId,
    playGroupName: reg.playGroup.name,
    teamNumber,
    accessCode: reg.accessCode,
    redirect: buildFeriaSalaRedirect(session.courseId, reg.playGroupId),
    magicLoginToken: magic,
    existing: true,
  };
}

export async function generateUniqueRoomCode(courseId: string): Promise<string> {
  const db = getForgeDb();
  for (let attempt = 0; attempt < 24; attempt++) {
    const roomCode = generateFeriaCode(6);
    const exists = await db.forgeFeriaSession.findFirst({
      where: { courseId, roomCode },
      select: { id: true },
    });
    if (!exists) return roomCode;
  }
  throw new Error('forge.feria.codeGenFailed');
}
