export const dynamic = 'force-dynamic';

import { NextRequest, NextResponse } from 'next/server';
import { getForgeDb } from '@/lib/forge/db';
import { getForgeCourseAccess } from '@/lib/forge/facilitator-access';
import { generateUniqueRoomCode, normalizeRoomCode } from '@/lib/forge/feria-kiosk';
import { loadCourseForTenant, requireForgeTenant } from '@/lib/forge/tenant';

type Ctx = { params: Promise<{ id: string }> };

export async function GET(_req: NextRequest, ctx: Ctx) {
  try {
    const tenant = await requireForgeTenant();
    if (!tenant) return NextResponse.json({ error: 'Não autorizado' }, { status: 401 });
    const { id: courseId } = await ctx.params;
    const course = await loadCourseForTenant(courseId, tenant);
    if (!course) return NextResponse.json({ error: 'Curso não encontrado' }, { status: 404 });

    const sessions = await getForgeDb().forgeFeriaSession.findMany({
      where: { courseId },
      orderBy: { createdAt: 'desc' },
      include: {
        _count: { select: { registrations: true } },
        playGroups: {
          where: { autoGenerated: true },
          orderBy: { createdAt: 'asc' },
          include: {
            _count: { select: { enrollments: true } },
            feriaRegistrations: {
              select: {
                id: true,
                name: true,
                email: true,
                accessCode: true,
                playGroupId: true,
                ageRange: true,
                gender: true,
                locale: true,
                registeredAt: true,
              },
              orderBy: { registeredAt: 'asc' },
            },
          },
        },
      },
    });

    return NextResponse.json({
      sessions: sessions.map((s) => ({
        id: s.id,
        roomCode: s.roomCode,
        title: s.title,
        teamSize: s.teamSize,
        active: s.active,
        participantCount: s._count.registrations,
        entryUrl: `/expedicion/entrar?room=${encodeURIComponent(s.roomCode)}`,
        groups: s.playGroups.map((g, idx) => ({
          id: g.id,
          name: g.name,
          teamNumber: idx + 1,
          memberCount: g._count.enrollments,
          members: g.feriaRegistrations.map((r) => ({
            id: r.id,
            name: r.name,
            email: r.email,
            accessCode: r.accessCode,
            ageRange: r.ageRange,
            gender: r.gender,
            locale: r.locale,
            registeredAt: r.registeredAt.toISOString(),
          })),
        })),
      })),
    });
  } catch (e) {
    return NextResponse.json({ error: e instanceof Error ? e.message : 'Erro' }, { status: 500 });
  }
}

export async function POST(req: NextRequest, ctx: Ctx) {
  try {
    const tenant = await requireForgeTenant();
    if (!tenant) return NextResponse.json({ error: 'Não autorizado' }, { status: 401 });
    const { id: courseId } = await ctx.params;
    const course = await loadCourseForTenant(courseId, tenant);
    if (!course) return NextResponse.json({ error: 'Curso não encontrado' }, { status: 404 });

    const access = await getForgeCourseAccess(
      tenant.userId,
      course.companyId,
      course.id,
      course.createdById
    );
    if (!access.canFacilitate) {
      return NextResponse.json({ error: 'Sin permiso' }, { status: 403 });
    }

    const body = (await req.json()) as {
      title?: string;
      teamSize?: number;
      roomCode?: string;
      sessionId?: string;
      createEmptyGroup?: boolean;
      registrationId?: string;
      playGroupId?: string;
      active?: boolean;
    };

    if (body.createEmptyGroup && body.sessionId) {
      const session = await getForgeDb().forgeFeriaSession.findFirst({
        where: { id: body.sessionId, courseId },
      });
      if (!session) {
        return NextResponse.json({ error: 'Sessão não encontrada' }, { status: 404 });
      }

      const existing = await getForgeDb().forgePlayGroup.count({
        where: { feriaSessionId: session.id },
      });
      const teamNumber = existing + 1;
      const { randomBytes } = await import('crypto');
      const inviteToken = randomBytes(24).toString('base64url');
      const expires = new Date();
      expires.setDate(expires.getDate() + 30);

      const group = await getForgeDb().forgePlayGroup.create({
        data: {
          courseId,
          name: `Equipo ${teamNumber}`,
          mode: 'live_team',
          feriaSessionId: session.id,
          autoGenerated: true,
          inviteToken,
          inviteExpiresAt: expires,
        },
      });

      return NextResponse.json(
        { group: { id: group.id, name: group.name, teamNumber } },
        { status: 201 }
      );
    }

    const teamSize =
      typeof body.teamSize === 'number' && body.teamSize >= 2 && body.teamSize <= 8
        ? Math.floor(body.teamSize)
        : 4;

    let roomCode = body.roomCode ? normalizeRoomCode(body.roomCode) : '';
    if (roomCode) {
      const taken = await getForgeDb().forgeFeriaSession.findFirst({
        where: { courseId, roomCode },
      });
      if (taken) {
        return NextResponse.json({ error: 'forge.feria.roomTaken' }, { status: 409 });
      }
    } else {
      roomCode = await generateUniqueRoomCode(courseId);
    }

    const session = await getForgeDb().forgeFeriaSession.create({
      data: {
        courseId,
        roomCode,
        title: body.title?.trim() || null,
        teamSize,
        active: true,
      },
    });

    return NextResponse.json(
      {
        session: {
          id: session.id,
          roomCode: session.roomCode,
          title: session.title,
          teamSize: session.teamSize,
          entryUrl: `/expedicion/entrar?room=${encodeURIComponent(session.roomCode)}`,
        },
      },
      { status: 201 }
    );
  } catch (e) {
    return NextResponse.json({ error: e instanceof Error ? e.message : 'Erro' }, { status: 500 });
  }
}

export async function PATCH(req: NextRequest, ctx: Ctx) {
  try {
    const tenant = await requireForgeTenant();
    if (!tenant) return NextResponse.json({ error: 'Não autorizado' }, { status: 401 });
    const { id: courseId } = await ctx.params;
    const course = await loadCourseForTenant(courseId, tenant);
    if (!course) return NextResponse.json({ error: 'Curso não encontrado' }, { status: 404 });

    const access = await getForgeCourseAccess(
      tenant.userId,
      course.companyId,
      course.id,
      course.createdById
    );
    if (!access.canFacilitate) {
      return NextResponse.json({ error: 'Sin permiso' }, { status: 403 });
    }

    const body = (await req.json()) as {
      sessionId?: string;
      active?: boolean;
      registrationId?: string;
      playGroupId?: string;
    };

    if (body.registrationId && body.playGroupId) {
      const reg = await getForgeDb().forgeFeriaRegistration.findFirst({
        where: { id: body.registrationId, session: { courseId } },
        select: { id: true, userId: true, sessionId: true },
      });
      const group = await getForgeDb().forgePlayGroup.findFirst({
        where: {
          id: body.playGroupId,
          courseId,
          feriaSessionId: reg?.sessionId ?? '__none__',
        },
      });
      if (!reg || !group) {
        return NextResponse.json({ error: 'Registro ou grupo inválido' }, { status: 404 });
      }

      const targetCount = await getForgeDb().forgeFeriaRegistration.count({
        where: { playGroupId: group.id, id: { not: reg.id } },
      });
      const session = await getForgeDb().forgeFeriaSession.findUnique({
        where: { id: reg.sessionId },
        select: { teamSize: true },
      });
      if (session && targetCount >= session.teamSize) {
        return NextResponse.json({ error: 'forge.feria.teamFull' }, { status: 409 });
      }

      await getForgeDb().$transaction([
        getForgeDb().forgeFeriaRegistration.update({
          where: { id: reg.id },
          data: { playGroupId: group.id },
        }),
        getForgeDb().forgeEnrollment.updateMany({
          where: { courseId, userId: reg.userId },
          data: { playGroupId: group.id },
        }),
      ]);

      return NextResponse.json({ ok: true });
    }

    const sessionId = body.sessionId?.trim();
    if (!sessionId) {
      return NextResponse.json({ error: 'sessionId requerido' }, { status: 400 });
    }

    const session = await getForgeDb().forgeFeriaSession.findFirst({
      where: { id: sessionId, courseId },
    });
    if (!session) return NextResponse.json({ error: 'Sessão não encontrada' }, { status: 404 });

    const updated = await getForgeDb().forgeFeriaSession.update({
      where: { id: session.id },
      data: { active: body.active !== false },
    });

    return NextResponse.json({ session: { id: updated.id, active: updated.active } });
  } catch (e) {
    return NextResponse.json({ error: e instanceof Error ? e.message : 'Erro' }, { status: 500 });
  }
}
