ALTER TABLE "ForgeCourse" ADD COLUMN IF NOT EXISTS "libroOcrText" TEXT;
ALTER TABLE "ForgeCourse" ADD COLUMN IF NOT EXISTS "libroOcrStatus" TEXT;
ALTER TABLE "ForgeCourse" ADD COLUMN IF NOT EXISTS "libroOcrAt" TIMESTAMP(3);
ALTER TABLE "ForgeCourse" ADD COLUMN IF NOT EXISTS "libroOcrMeta" JSONB;

ALTER TABLE "ForgeLiveSession" ADD COLUMN IF NOT EXISTS "recordingUrl" TEXT;
ALTER TABLE "ForgeLiveSession" ADD COLUMN IF NOT EXISTS "recordingNotes" TEXT;
