/** Mapa validado: Rural Commerce Reporting Tool v.agust — Impulsa Mipymes Los Santos */

export type ReportingToolTag =
  | 'same_essence'
  | 'official_dos'
  | 'to_be_designed'
  | 'project_only_internal';

export type ReportingToolBlock = 'project_results' | 'cross_cutting';

export type ReportingToolSeedLine = {
  order: number;
  block: ReportingToolBlock;
  resultContext: string;
  indicatorText: string;
  isDos: boolean;
  tag: ReportingToolTag;
  baseline: string;
  target: string;
  siepHint: string;
  notes: string;
  /** Códigos EG / palavras-chave para auto-link ao Objective do logframe */
  matchHints: string[];
};

export const IMPULSA_LOS_SANTOS_REPORTING_TOOL = {
  title: 'Rural Commerce — Reporting Tool',
  version: 'v.agust',
  sourceFileName: 'Rural Commerce  - Reporting Tool v.agust.xlsx',
  notes:
    'Camada oficial de reporte (paralela ao PMP/logframe). TBD = to_be_designed. DoS reporta-se sempre como linha própria.',
  lines: [
    {
      order: 1,
      block: 'project_results',
      resultContext: 'Outcome 1',
      indicatorText:
        'O1.1 Number of participating MSMEs demonstrating improved business and financial-management capacity',
      isDos: false,
      tag: 'to_be_designed',
      baseline: '0',
      target: 'TBD',
      siepHint: 'Outcome R1 (só narrativa)',
      notes: 'Outcome novo; target TBD',
      matchHints: [],
    },
    {
      order: 2,
      block: 'project_results',
      resultContext: 'Outcome 1',
      indicatorText: 'O1.2 Number of participating MSMEs routinely using production traceability tools',
      isDos: false,
      tag: 'to_be_designed',
      baseline: '0',
      target: 'TBD',
      siepHint: '—',
      notes: 'Outcome novo; target TBD',
      matchHints: [],
    },
    {
      order: 3,
      block: 'project_results',
      resultContext: 'Outcome 1',
      indicatorText: 'O1.3 Number of participating MSMEs implementing export-readiness improvements',
      isDos: false,
      tag: 'to_be_designed',
      baseline: '0',
      target: 'TBD',
      siepHint: '—',
      notes: 'Outcome novo; target TBD',
      matchHints: [],
    },
    {
      order: 4,
      block: 'project_results',
      resultContext: 'Output 1.1',
      indicatorText:
        '1.1.1. Number of cooperative leadership and MSME staff trained in international sustainable business models, export basics, and digital tools',
      isDos: false,
      tag: 'same_essence',
      baseline: '0',
      target: '60',
      siepHint: 'Atividades treino A1.2; não é o mesmo que EG.2-1',
      notes: 'Conta pessoas treinadas; evidência sob treino no PMP',
      matchHints: ['staff trained', 'cooperative leadership', 'digital tool'],
    },
    {
      order: 5,
      block: 'project_results',
      resultContext: 'Output 1.1',
      indicatorText:
        '1.1.2. Number of participating enterprises receiving individualized coaching on financial management, basic costing, and digital tool adoption',
      isDos: false,
      tag: 'same_essence',
      baseline: '0',
      target: '10',
      siepHint: 'Custom coaching (target 10)',
      notes: 'Mesma essência do coaching no PMP/SIEP',
      matchHints: ['individualized coaching', 'coaching on financial'],
    },
    {
      order: 6,
      block: 'project_results',
      resultContext: 'Output 1.1',
      indicatorText: '1.1.3. Number of business-improvement plans developed.',
      isDos: false,
      tag: 'same_essence',
      baseline: '0',
      target: '60',
      siepHint: 'Custom business improvement plans (60)',
      notes: 'Mesma essência business improvement plans',
      matchHints: ['business improvement plans'],
    },
    {
      order: 7,
      block: 'project_results',
      resultContext: 'Outcome 2',
      indicatorText: 'O2.1 Percentage of participating MSME staff using the shared maquila/bio-refinery.',
      isDos: false,
      tag: 'to_be_designed',
      baseline: '0',
      target: 'TBD',
      siepHint: 'Outcome R2 (só narrativa)',
      notes: 'Outcome novo; target TBD',
      matchHints: [],
    },
    {
      order: 8,
      block: 'project_results',
      resultContext: 'Output 2.1',
      indicatorText:
        '2.1.1 Percentage of completion of the shared maquila/bio-refinery implementation process.',
      isDos: false,
      tag: 'same_essence',
      baseline: '0',
      target: '100%',
      siepHint: 'Existence design / equipment / protocols',
      notes: 'Fundiu vários Yes/No do PMP num % de conclusão',
      matchHints: ['technical design document', 'equipment items procured', 'validated processing protocols'],
    },
    {
      order: 9,
      block: 'project_results',
      resultContext: 'Output 2.1',
      indicatorText: '2.1.2. Number of staff trained in maquila operation and quality control',
      isDos: false,
      tag: 'to_be_designed',
      baseline: '0',
      target: 'TBD',
      siepHint: 'Custom staff trained maquila (2)',
      notes: 'Mesma essência; target TBD → aguardar definição',
      matchHints: ['staff trained in maquila'],
    },
    {
      order: 10,
      block: 'project_results',
      resultContext: 'Output 2.1',
      indicatorText:
        '2.1.3 Governance and cost-sharing framework for the shared maquila established and approved.',
      isDos: false,
      tag: 'same_essence',
      baseline: '0',
      target: '1',
      siepHint: 'Existence of governance agreement',
      notes: 'Governance/cost-sharing; no SIEP era existence Yes/No',
      matchHints: ['governance agreement'],
    },
    {
      order: 11,
      block: 'project_results',
      resultContext: 'Outcome 3',
      indicatorText: 'O3.1 Percentage of participating MSMEs staff using monitoring tools and data.',
      isDos: false,
      tag: 'to_be_designed',
      baseline: '0',
      target: 'TBD',
      siepHint: 'Outcome R3 (só narrativa)',
      notes: 'Outcome novo; target TBD',
      matchHints: [],
    },
    {
      order: 12,
      block: 'project_results',
      resultContext: 'Output 3.1',
      indicatorText: '3.1.1 Number of monitoring kits installed, tested, and calibrated',
      isDos: false,
      tag: 'same_essence',
      baseline: '0',
      target: '1',
      siepHint: 'Custom monitoring kits (1)',
      notes: 'Mesmo indicador kits monitoring',
      matchHints: ['monitoring kits installed'],
    },
    {
      order: 13,
      block: 'project_results',
      resultContext: 'Output 3.1',
      indicatorText: '3.1.2 Number of staff trained in use and maintenance of monitoring tools.',
      isDos: false,
      tag: 'same_essence',
      baseline: '0',
      target: '2',
      siepHint: 'Custom staff trained monitoring (2)',
      notes: 'Mesmo indicador staff trained monitoring',
      matchHints: ['staff trained in use and maintenance of monitoring'],
    },
    {
      order: 14,
      block: 'project_results',
      resultContext: 'Outcome 4',
      indicatorText:
        'O4.1 Number of participating MSMEs actively participating in the collaborative commercialization network by the end of the project.',
      isDos: false,
      tag: 'to_be_designed',
      baseline: '0',
      target: 'TBD',
      siepHint: 'Outcome R4 (só narrativa)',
      notes: 'Outcome novo; target TBD',
      matchHints: [],
    },
    {
      order: 15,
      block: 'project_results',
      resultContext: 'Outcome 4',
      indicatorText:
        'O4.2 Number of participating MSMEs with improved access to national and international markets through the implementation of joint commercialization strategies, export-readiness support, regulatory compliance guidance, business networking, and market-specific capacity building.',
      isDos: false,
      tag: 'to_be_designed',
      baseline: '0',
      target: 'TBD',
      siepHint: 'Outcome R4 (só narrativa)',
      notes: 'Outcome novo; target TBD',
      matchHints: [],
    },
    {
      order: 16,
      block: 'project_results',
      resultContext: 'Output 4.1',
      indicatorText:
        '4.1.1 Collaborative commercialization governance framework and commercialization mechanism is jointly developed and approved by the members',
      isDos: false,
      tag: 'same_essence',
      baseline: '0',
      target: '1',
      siepHint: 'Existence of governance framework document',
      notes: 'Governance framework approved',
      matchHints: ['governance framework document'],
    },
    {
      order: 17,
      block: 'project_results',
      resultContext: 'Output 4.1',
      indicatorText: '4.1.2 Number of marketing strategies designed',
      isDos: false,
      tag: 'same_essence',
      baseline: '0',
      target: '1',
      siepHint: 'Custom marketing strategies (1)',
      notes: 'Mesmo marketing strategies',
      matchHints: ['marketing strategies designed'],
    },
    {
      order: 18,
      block: 'project_results',
      resultContext: 'Output 4.1',
      indicatorText:
        "4.1.3 Number of strategic organizations engaged through formal meetings to support participating MSMEs' access to the U.S. market.",
      isDos: false,
      tag: 'to_be_designed',
      baseline: '0',
      target: 'TBD',
      siepHint: '—',
      notes: 'Novo; target TBD',
      matchHints: [],
    },
    {
      order: 19,
      block: 'project_results',
      resultContext: 'Output 4.1',
      indicatorText: '4.1.4 Collaborative commercialization mechanism  piloted.',
      isDos: false,
      tag: 'same_essence',
      baseline: '0%',
      target: '100%',
      siepHint: 'Existence of documented commercialization mechanism',
      notes: '% piloto vs existence Yes/No do mechanism no PMP',
      matchHints: ['collaborative commercialization mechanism'],
    },
    {
      order: 20,
      block: 'cross_cutting',
      resultContext: 'Standard indicators - Cross Cutting',
      indicatorText: 'EG.2-1 - Person-hours of USG supported training completed in trade and investment.',
      isDos: true,
      tag: 'official_dos',
      baseline: '0',
      target: '80',
      siepHint: 'EG.2-1 no SIEP (80) — evidência pode alimentar',
      notes: 'DoS standard; reportar sempre',
      matchHints: ['EG.2-1', 'Person-hours of USG'],
    },
    {
      order: 21,
      block: 'cross_cutting',
      resultContext: 'Standard indicators - Cross Cutting',
      indicatorText: 'EG.2.2-1. Number of firms receiving USG-funded technical assistance to export.',
      isDos: true,
      tag: 'official_dos',
      baseline: '0',
      target: '16',
      siepHint: 'EG.2.2-1 no SIEP (60) — NÃO fundir; evidência contribui',
      notes: 'DoS standard; reportar sempre mesmo com similar no projeto',
      matchHints: ['EG.2.2-1', 'technical assistance to export'],
    },
    {
      order: 22,
      block: 'cross_cutting',
      resultContext: 'Standard indicators - Cross Cutting',
      indicatorText:
        'EG.3.2-24 Number of individuals in the agriculture and food system who have applied improvement management practices or technologies with USG assistance',
      isDos: true,
      tag: 'official_dos',
      baseline: '0',
      target: '60',
      siepHint: 'EG.3.2-24 no SIEP (60)',
      notes: 'DoS standard',
      matchHints: ['EG.3.2-24'],
    },
    {
      order: 23,
      block: 'cross_cutting',
      resultContext: 'Standard indicators - Cross Cutting',
      indicatorText:
        'EG.5.2-2 Number of private sector firms that have improved management practices or technologies as a result of USG assistance.',
      isDos: true,
      tag: 'official_dos',
      baseline: '0',
      target: '60',
      siepHint: 'EG.5.2-2 no SIEP (60)',
      notes: 'DoS standard',
      matchHints: ['EG.5.2-2'],
    },
    {
      order: 24,
      block: 'cross_cutting',
      resultContext: 'Standard indicators - Cross Cutting',
      indicatorText: 'EG.5-3 - Number of microenterprises supported by USG assistance',
      isDos: true,
      tag: 'official_dos',
      baseline: '0',
      target: '59',
      siepHint: 'EG.5-3 no SIEP (59)',
      notes: 'DoS standard',
      matchHints: ['EG.5-3'],
    },
    {
      order: 25,
      block: 'cross_cutting',
      resultContext: 'Standard indicators - Cross Cutting',
      indicatorText: 'EG.5-12 - Number of small and medium-sized enterprises supported by USG assistance',
      isDos: true,
      tag: 'official_dos',
      baseline: '0',
      target: '1',
      siepHint: '—',
      notes: 'DoS standard; não estava no SIEP',
      matchHints: ['EG.5-12'],
    },
    {
      order: 26,
      block: 'cross_cutting',
      resultContext: 'Standard indicators - Cross Cutting',
      indicatorText: 'EG.5-12-a Number of male entrepreneurs',
      isDos: true,
      tag: 'official_dos',
      baseline: '0',
      target: '45',
      siepHint: '—',
      notes: 'Desagregação DoS EG.5-12',
      matchHints: ['EG.5-12-a', 'male entrepreneurs'],
    },
    {
      order: 27,
      block: 'cross_cutting',
      resultContext: 'Standard indicators - Cross Cutting',
      indicatorText: 'EG.5-12-b Number of female entrepreneurs',
      isDos: true,
      tag: 'official_dos',
      baseline: '0',
      target: '15',
      siepHint: '—',
      notes: 'Desagregação DoS EG.5-12',
      matchHints: ['EG.5-12-b', 'female entrepreneurs'],
    },
    {
      order: 28,
      block: 'cross_cutting',
      resultContext: 'Standard indicators - Cross Cutting',
      indicatorText:
        'EG.6-15 Percentage of individuals with better employment following participation in USG-assisted workforce development programs',
      isDos: true,
      tag: 'official_dos',
      baseline: '0',
      target: '30%',
      siepHint: 'EG.6-15 no SIEP (30%)',
      notes: 'DoS standard',
      matchHints: ['EG.6-15'],
    },
    {
      order: 29,
      block: 'cross_cutting',
      resultContext: 'Standard indicators - Cross Cutting',
      indicatorText:
        'Custom 2.a. Number of written proposals with La RED or its members to exchange knowledge, cooperate or to obtain funds (grants)',
      isDos: true,
      tag: 'to_be_designed',
      baseline: '0',
      target: 'TBD',
      siepHint: '—',
      notes: 'Obrigação oficial DoS/programa (método TBD)',
      matchHints: [],
    },
    {
      order: 30,
      block: 'cross_cutting',
      resultContext: 'Standard indicators - Cross Cutting',
      indicatorText: 'Custom 4. Number of businesses benefiting from the Empower Innovation Challenge trainings.',
      isDos: true,
      tag: 'to_be_designed',
      baseline: '0',
      target: 'TBD',
      siepHint: '—',
      notes: 'Obrigação oficial DoS/programa (método TBD)',
      matchHints: [],
    },
    {
      order: 31,
      block: 'cross_cutting',
      resultContext: 'Standard indicators - Cross Cutting',
      indicatorText:
        'Custom 5. Number of training sessions provided by the Organization (Small Grantee) for La RED members.',
      isDos: true,
      tag: 'official_dos',
      baseline: '0',
      target: '1',
      siepHint: '—',
      notes: 'Custom programa La RED trainings',
      matchHints: [],
    },
    {
      order: 32,
      block: 'cross_cutting',
      resultContext: 'Standard indicators - Cross Cutting',
      indicatorText: 'Custom 6. Number of public private partnerships formed as a result of USG  assistance',
      isDos: true,
      tag: 'to_be_designed',
      baseline: '0',
      target: 'TBD',
      siepHint: '—',
      notes: 'Obrigação oficial DoS/programa (método TBD)',
      matchHints: [],
    },
    {
      order: 33,
      block: 'cross_cutting',
      resultContext: 'Standard indicators - Cross Cutting',
      indicatorText: 'Custom 6.a. Percentage of beneficiary firms that interact with 1 partner of the partnership',
      isDos: true,
      tag: 'to_be_designed',
      baseline: '0',
      target: 'TBD',
      siepHint: '—',
      notes: 'Obrigação oficial DoS/programa (método TBD)',
      matchHints: [],
    },
    {
      order: 34,
      block: 'cross_cutting',
      resultContext: 'Standard indicators - Cross Cutting',
      indicatorText: 'Custom 6.b. Number of partnerships to expand business with USA companies.',
      isDos: true,
      tag: 'to_be_designed',
      baseline: '0',
      target: 'TBD',
      siepHint: '—',
      notes: 'Obrigação oficial DoS/programa (método TBD)',
      matchHints: [],
    },
    {
      order: 35,
      block: 'cross_cutting',
      resultContext: 'Standard indicators - Cross Cutting',
      indicatorText: 'Custom 14 - Number of full-time equivalent (FTE) jobs created with USG TBD assistance.',
      isDos: true,
      tag: 'official_dos',
      baseline: '0',
      target: '0',
      siepHint: '—',
      notes: 'Custom programa jobs; target 0',
      matchHints: [],
    },
    {
      order: 36,
      block: 'cross_cutting',
      resultContext: 'Standard indicators - Cross Cutting',
      indicatorText:
        'Custom 15. Number of micro, small and medium enterprises (firms), including  farmers, receiving business development services from USG assistance',
      isDos: true,
      tag: 'official_dos',
      baseline: '0',
      target: '60',
      siepHint: 'Custom 15 (60) — evidência alimenta; linha oficial separada',
      notes: 'DoS/programa; reportar sempre',
      matchHints: ['Custom 15', 'business development services'],
    },
    {
      order: 37,
      block: 'cross_cutting',
      resultContext: 'Standard indicators - Cross Cutting',
      indicatorText:
        'Custom 16 - Number of days of USG-funded technical training in registration and operation of micro- or small enterprises provided to counterparts',
      isDos: true,
      tag: 'to_be_designed',
      baseline: '0',
      target: 'TBD',
      siepHint: '—',
      notes: 'Obrigação oficial DoS/programa (método TBD)',
      matchHints: [],
    },
    {
      order: 38,
      block: 'cross_cutting',
      resultContext: 'Standard indicators - Cross Cutting',
      indicatorText:
        'Custom 17. Number of micro, small and medium enterprises (MSMEs), including  farmers, receiving business development services from La RED members',
      isDos: true,
      tag: 'official_dos',
      baseline: '0',
      target: '28',
      siepHint: '—',
      notes: 'Custom programa La RED BDS',
      matchHints: [],
    },
    {
      order: 39,
      block: 'cross_cutting',
      resultContext: 'Standard indicators - Cross Cutting',
      indicatorText: 'Custom 18a. Investments made by Beneficiaries (USD) that are a result of the project',
      isDos: true,
      tag: 'to_be_designed',
      baseline: '0',
      target: 'TBD',
      siepHint: '—',
      notes: 'Obrigação oficial DoS/programa (método TBD)',
      matchHints: [],
    },
    {
      order: 40,
      block: 'cross_cutting',
      resultContext: 'Standard indicators - Cross Cutting',
      indicatorText: 'Custom 18b. Savings or economic benefits (USD) that are a result of the project',
      isDos: true,
      tag: 'to_be_designed',
      baseline: '0',
      target: 'TBD',
      siepHint: '—',
      notes: 'Obrigação oficial DoS/programa (método TBD)',
      matchHints: [],
    },
    {
      order: 41,
      block: 'cross_cutting',
      resultContext: 'Standard indicators - Cross Cutting',
      indicatorText: 'Custom 18c. Number of MSMEs that report an increase of productivity or competitiveness',
      isDos: true,
      tag: 'official_dos',
      baseline: '0',
      target: '10',
      siepHint: '—',
      notes: 'Custom programa productivity/competitiveness',
      matchHints: [],
    },
    {
      order: 42,
      block: 'cross_cutting',
      resultContext: 'Standard indicators - Cross Cutting',
      indicatorText:
        'Custom 18d. Number of new USA companies with achieved new business or business agreements (as suppliers or clients) with the beneficiaries',
      isDos: true,
      tag: 'to_be_designed',
      baseline: '0',
      target: 'TBD',
      siepHint: '—',
      notes: 'Obrigação oficial DoS/programa (método TBD)',
      matchHints: [],
    },
  ] satisfies ReportingToolSeedLine[],
};
